// El King Store — shared product catalog
// آخر تحديث: ١‏/١٠‏/٢٠٢٦، ١٠:٠٩:٤٥ م
window.ELKING_PRODUCTS = [
  {
    "id": 490,
    "cat": "new",
    "name": "",
    "storage": "",
    "color": "",
    "colorHex": "",
    "brand": "",
    "price": "",
    "originalPrice": "",
    "description": "",
    "img": "",
    "imgs": [],
    "featured": false,
    "variants": [],
    "inStock": true
  },
  {
    "id": 485,
    "cat": "used",
    "name": "Iphone 16pro max used s",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "65000",
    "originalPrice": "66000",
    "description": "16pro max\n91%",
    "img": "images/products/p485_0_z03a4i.jpg",
    "imgs": [
      "images/products/p485_0_z03a4i.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "ممتاز"
  },
  {
    "id": 484,
    "cat": "used",
    "name": "Iphone 17pro max 256 used s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "92000",
    "originalPrice": "93000",
    "description": "17 promax\n256 /100%\n21شحنه",
    "img": "images/products/p484_0_ezxgy4.jpg",
    "imgs": [
      "images/products/p484_0_ezxgy4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 483,
    "cat": "used",
    "name": "iphone 17 promax 256 used s",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "92000",
    "originalPrice": "93000",
    "description": "17 promax\n256/100%\n38 شحنه",
    "img": "images/products/p483_0_nqmil5.jpg",
    "imgs": [
      "images/products/p483_0_nqmil5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 482,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "128",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "11000",
    "originalPrice": "12000",
    "description": "iPhone 11 \nGB: 128\nBi: 77%\nScreen",
    "img": "images/products/p482_0_aps4f0.jpg",
    "imgs": [
      "images/products/p482_0_aps4f0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "77%",
    "condition": "ممتاز"
  },
  {
    "id": 481,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "9000",
    "originalPrice": "10000",
    "description": "iPhone 11 \nGB: 128\nBi: 100%\nBattery \nFace ID",
    "img": "images/products/p481_0_dq0m9q.jpg",
    "imgs": [
      "images/products/p481_0_dq0m9q.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "جيد جدا"
  },
  {
    "id": 480,
    "cat": "used",
    "name": "Iphone 16pro max 256 used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "65000",
    "originalPrice": "65500",
    "description": "iPhone 16 Pro Max\nGB: 256\nBi: 91%",
    "img": "images/products/p480_0_s6jbvz.jpg",
    "imgs": [
      "images/products/p480_0_s6jbvz.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "ممتاز"
  },
  {
    "id": 479,
    "cat": "used",
    "name": "Ipad A16 128 used",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "18500",
    "originalPrice": "19000",
    "description": "ipad A16\n 128G \nwifi\n شحنه ١\nLike new",
    "img": "images/products/p479_0_my9ivl.jpg",
    "imgs": [
      "images/products/p479_0_my9ivl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 478,
    "cat": "used",
    "name": "Iphone 16pro max 256 used u",
    "storage": "",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "",
    "price": "67000",
    "originalPrice": "67500",
    "description": "iPhone 16 Pro Max\nGB: 256\nBi: 93%",
    "img": "images/products/p478_0_vlyalh.jpg",
    "imgs": [
      "images/products/p478_0_vlyalh.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "93%",
    "condition": "ممتاز"
  },
  {
    "id": 476,
    "cat": "used",
    "name": "iphone 17 promax 256 used",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "83000",
    "originalPrice": "84000",
    "description": "17pro max \n256\n94%\nWith box",
    "img": "images/products/p476_0_v9a4gw.jpg",
    "imgs": [
      "images/products/p476_0_v9a4gw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "94%",
    "condition": "ممتاز"
  },
  {
    "id": 475,
    "cat": "used",
    "name": "Iphone 17pro max 256 used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "90000",
    "originalPrice": "91000",
    "description": "iPhone 17 Pro Max\nGB: 256\nBi: 100% (26🔌)",
    "img": "images/products/p475_0_ec0lja.jpg",
    "imgs": [
      "images/products/p475_0_ec0lja.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 474,
    "cat": "used",
    "name": "Iphone 17pro max 1TB used u",
    "storage": "1TB",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "110000",
    "originalPrice": "111000",
    "description": "iPhone 17 Pro Max \nGB: 1TB\nBi: 99% (180🔌)",
    "img": "images/products/p474_0_nmusde.jpg",
    "imgs": [
      "images/products/p474_0_nmusde.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "99%",
    "condition": "ممتاز"
  },
  {
    "id": 473,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "وردي",
    "colorHex": "#f9a8d4",
    "brand": "Apple",
    "price": "24000",
    "originalPrice": "24500",
    "description": "iPhone 13 \nGB: 128\nBi: 75%",
    "img": "images/products/p473_0_tkmiaf.jpg",
    "imgs": [
      "images/products/p473_0_tkmiaf.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "75%",
    "condition": "ممتاز"
  },
  {
    "id": 472,
    "cat": "used",
    "name": "Iphone 11 used z",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "15500",
    "originalPrice": "16000",
    "description": "ip 11 \n128 / 77%🔋\nNo box",
    "img": "images/products/p472_0_fed5zg.jpg",
    "imgs": [
      "images/products/p472_0_fed5zg.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "77%",
    "condition": "جيد جدا"
  },
  {
    "id": 471,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "24000",
    "originalPrice": "24500",
    "description": "iPhone 13 \nGB: 128\nBi: 78%\n2Sim",
    "img": "images/products/p471_0_j7msa3.jpg",
    "imgs": [
      "images/products/p471_0_j7msa3.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "78%",
    "condition": "ممتاز"
  },
  {
    "id": 470,
    "cat": "used",
    "name": "Iphone 16pro max used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "69000",
    "originalPrice": "70000",
    "description": "iPhone 16 Pro Max\nGB: 256\nBi: 95%",
    "img": "images/products/p470_0_y8309s.jpg",
    "imgs": [
      "images/products/p470_0_y8309s.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "95%",
    "condition": "ممتاز"
  },
  {
    "id": 469,
    "cat": "used",
    "name": "Iphone 11 used",
    "storage": "128",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "11000",
    "originalPrice": "12000",
    "description": "iPhone 11 \nGB: 128\nBi:100%\nBattery \nScreen",
    "img": "images/products/p469_0_jj9q7b.jpg",
    "imgs": [
      "images/products/p469_0_jj9q7b.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "جيد"
  },
  {
    "id": 468,
    "cat": "used",
    "name": "Iphone 17 pro max 512 used",
    "storage": "",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "100000",
    "originalPrice": "101000",
    "description": "17pro max used \n99%\nWithbox\n512\nNo tax",
    "img": "images/products/p468_0_yh2osx.jpg",
    "imgs": [
      "images/products/p468_0_yh2osx.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "99%",
    "condition": "ممتاز"
  },
  {
    "id": 467,
    "cat": "used",
    "name": "Honor x9d used z",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Honor",
    "price": "18500",
    "originalPrice": "19000",
    "description": "Honor x9d\n12 / 256 \nضمان ٥ شهور",
    "img": "images/products/p467_0_p7aphn.jpg",
    "imgs": [
      "images/products/p467_0_p7aphn.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 465,
    "cat": "used",
    "name": "Iphone 13 used z",
    "storage": "128",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "25000",
    "originalPrice": "25500",
    "description": "ip 13 \n128 / 82%\nNo box",
    "img": "images/products/p465_0_dv7xjs.jpg",
    "imgs": [
      "images/products/p465_0_dv7xjs.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "82%",
    "condition": "جيد"
  },
  {
    "id": 463,
    "cat": "used",
    "name": "Iphone 15 used",
    "storage": "128",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "39000",
    "originalPrice": "40000",
    "description": "Iphone 15 \n89%\nWith box \nNo tax",
    "img": "images/products/p463_0_jbgtck.jpg",
    "imgs": [
      "images/products/p463_0_jbgtck.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "89%",
    "condition": "ممتاز"
  },
  {
    "id": 462,
    "cat": "new",
    "name": "Ipad A16 256",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "apple",
    "price": "24500",
    "originalPrice": "25000",
    "description": "يتميز جهاز آيباد الجيل الحادي عشر (موديل 2025) بشريحة A16 Bionic القوية (4 نانومتر)، وشاشة Liquid Retina مقاس 10.9 أو 11 بوصة، وذاكرة رام 6 جيجابايت، مع كاميرات 12MP تدعم Center Stage، وبطارية تدوم لـ 10 ساعات، ويعد خياراً مثالياً للأداء السريع والسلس بأسعار معقولة",
    "img": "images/products/p462_0_h5j0t8.jpg",
    "imgs": [
      "images/products/p462_0_h5j0t8.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 461,
    "cat": "new",
    "name": "Infinix smart 20 3/64",
    "storage": "64",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Infinix",
    "price": "6200",
    "originalPrice": "6500",
    "description": "المعالج: ثماني النواة Helio G81 ULT تكنولوجيا 12 نانو\nالتخزين / الرام: 64/128 جيجا مع 4 جيجا رام\nالكاميرا: خلفية 8 م.ب / امامية 8 م.ب.\nالشاشة: 6.78 بوصة بدقة 720x1576 بكسل بها ثقب\nنظام التشغيل: اندرويد 16\nالبطارية: 5200 مللي أمبير",
    "img": "images/products/p461_0_y5xn06.jpg",
    "imgs": [
      "images/products/p461_0_y5xn06.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 460,
    "cat": "new",
    "name": "Infinix smart 20 4/128",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Infinix",
    "price": "6800",
    "originalPrice": "7000",
    "description": "المعالج: ثماني النواة Helio G81 ULT تكنولوجيا 12 نانو\nالتخزين / الرام: 64/128 جيجا مع 4 جيجا رام\nالكاميرا: خلفية 8 م.ب / امامية 8 م.ب.\nالشاشة: 6.78 بوصة بدقة 720x1576 بكسل بها ثقب\nنظام التشغيل: اندرويد 16\nالبطارية: 5200 مللي أمبير",
    "img": "images/products/p460_0_y5xn06.jpg",
    "imgs": [
      "images/products/p460_0_y5xn06.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 456,
    "cat": "used",
    "name": "Iphone 12 used z",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "17000",
    "originalPrice": "17500",
    "description": "ip 12 128\n78%",
    "img": "images/products/p456_0_okfsv4.jpg",
    "imgs": [
      "images/products/p456_0_okfsv4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "78%",
    "condition": "ممتاز"
  },
  {
    "id": 455,
    "cat": "used",
    "name": "Iphone 12 used z",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "17500",
    "originalPrice": "18000",
    "description": "ip 12 \n128 \n79%",
    "img": "images/products/p455_0_j1ll9m.jpg",
    "imgs": [
      "images/products/p455_0_j1ll9m.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "79%",
    "condition": "جيد جدا"
  },
  {
    "id": 454,
    "cat": "used",
    "name": "17pro max used",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "91000",
    "originalPrice": "92000",
    "description": "17pro max \n256\n100%\n120cycle",
    "img": "images/products/p454_0_4rlen2.jpg",
    "imgs": [
      "images/products/p454_0_4rlen2.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 453,
    "cat": "used",
    "name": "17pro max used k",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "92000",
    "originalPrice": "93000",
    "description": "17pro max\n256\n79cycle\nWith box \nNo tax",
    "img": "images/products/p453_0_s54hgt.jpg",
    "imgs": [
      "images/products/p453_0_s54hgt.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 452,
    "cat": "used",
    "name": "15pro max used u",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "50000",
    "originalPrice": "51000",
    "description": "iPhone 15 Pro Max\nGB: 256\nBi: 90%",
    "img": "images/products/p452_0_ncq0ku.jpg",
    "imgs": [
      "images/products/p452_0_ncq0ku.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "90%",
    "condition": "ممتاز"
  },
  {
    "id": 451,
    "cat": "used",
    "name": "Ipad m5 pro usedu",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "50000",
    "originalPrice": "51000",
    "description": "iPad M5 Pro \nGB: 256\nBi: 100% \nActive",
    "img": "images/products/p451_0_be2go5.jpg",
    "imgs": [
      "images/products/p451_0_be2go5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 450,
    "cat": "used",
    "name": "Iphone XR used u",
    "storage": "64",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "7000",
    "originalPrice": "7500",
    "description": "iPhone XR\nGB:64%\nBi: 75%",
    "img": "images/products/p450_0_n5l5fc.jpg",
    "imgs": [
      "images/products/p450_0_n5l5fc.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "75%",
    "condition": "ممتاز"
  },
  {
    "id": 449,
    "cat": "used",
    "name": "Iphone X used u",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "10000",
    "originalPrice": "11000",
    "description": "iPhone X\nGB: 256\nBi: 82%",
    "img": "images/products/p449_0_2w4mt5.jpg",
    "imgs": [
      "images/products/p449_0_2w4mt5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "82%",
    "condition": "ممتاز"
  },
  {
    "id": 448,
    "cat": "used",
    "name": "Xs max used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "13000",
    "originalPrice": "13500",
    "description": "iPhone XSMAX \nGB: 256\nBi: 78%\nScreen \nظهر",
    "img": "images/products/p448_0_di5ebq.jpg",
    "imgs": [
      "images/products/p448_0_di5ebq.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "78%",
    "condition": "جيد"
  },
  {
    "id": 447,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "16500",
    "originalPrice": "17000",
    "description": "iPhone 11\nGB: 128\nBi: 83%",
    "img": "images/products/p447_0_r8mu5f.jpg",
    "imgs": [
      "images/products/p447_0_r8mu5f.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "83%",
    "condition": "جيد جدا"
  },
  {
    "id": 446,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "13000",
    "originalPrice": "13500",
    "description": "iPhone 11 \nGB: 128\nBi: 70%",
    "img": "images/products/p446_0_r8mu5f.jpg",
    "imgs": [
      "images/products/p446_0_r8mu5f.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "70%",
    "condition": "جيد"
  },
  {
    "id": 445,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "128",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "14500",
    "originalPrice": "15000",
    "description": "iPhone 11 \nGB: 128\nBi: 75%",
    "img": "images/products/p445_0_m596wf.jpg",
    "imgs": [
      "images/products/p445_0_m596wf.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "75%",
    "condition": "ممتاز"
  },
  {
    "id": 444,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "128",
    "color": "أحمر",
    "colorHex": "#dc2626",
    "brand": "Apple",
    "price": "12000",
    "originalPrice": "13000",
    "description": "iPhone 11 \nGB: 128\nBi: 76%",
    "img": "images/products/p444_0_25634x.jpg",
    "imgs": [
      "images/products/p444_0_25634x.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76%",
    "condition": "جيد"
  },
  {
    "id": 443,
    "cat": "used",
    "name": "Iphone 11 used u",
    "storage": "256",
    "color": "أحمر",
    "colorHex": "#dc2626",
    "brand": "Apple",
    "price": "10000",
    "originalPrice": "10500",
    "description": "iPhone 11 \nGB: 256\nBi: 70%",
    "img": "images/products/p443_0_zfbs0k.jpg",
    "imgs": [
      "images/products/p443_0_zfbs0k.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "70%",
    "condition": "جيد جدا"
  },
  {
    "id": 442,
    "cat": "used",
    "name": "Iphone 12 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "9000",
    "originalPrice": "9500",
    "description": "iPhone 12 \nGB: 128\nBi: 94%\nTax",
    "img": "images/products/p442_0_iwjqk1.jpg",
    "imgs": [
      "images/products/p442_0_iwjqk1.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "94%",
    "condition": "ممتاز"
  },
  {
    "id": 440,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "256",
    "color": "وردي",
    "colorHex": "#f9a8d4",
    "brand": "Apple",
    "price": "19000",
    "originalPrice": "19500",
    "description": "iPhone 13 \nGB: 256\nBi: 76%\nScreen",
    "img": "images/products/p440_0_pheqii.jpg",
    "imgs": [
      "images/products/p440_0_pheqii.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76%",
    "condition": "جيد"
  },
  {
    "id": 439,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "25000",
    "originalPrice": "25500",
    "description": "iPhone 13 \nGB: 256\nBi: 75%",
    "img": "images/products/p439_0_f0i6ec.jpg",
    "imgs": [
      "images/products/p439_0_f0i6ec.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "75%",
    "condition": "جيد"
  },
  {
    "id": 438,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "29500",
    "description": "iPhone 13 \nGB: 128\nBi: 91%",
    "img": "images/products/p438_0_f0i6ec.jpg",
    "imgs": [
      "images/products/p438_0_f0i6ec.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "ممتاز"
  },
  {
    "id": 437,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "25000",
    "originalPrice": "25500",
    "description": "iPhone 13 \nGB: 128\nBi: 100%\nActive \nTax",
    "img": "images/products/p437_0_9kz1l5.jpg",
    "imgs": [
      "images/products/p437_0_9kz1l5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 436,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "25000",
    "originalPrice": "25500",
    "description": "iPhone 13 \nGB: 128\nBi: 87%",
    "img": "images/products/p436_0_ssrw10.jpg",
    "imgs": [
      "images/products/p436_0_ssrw10.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "87%",
    "condition": "جيد"
  },
  {
    "id": 435,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "24000",
    "originalPrice": "24500",
    "description": "iPhone 13 \nGB: 128\nBi: 84%",
    "img": "images/products/p435_0_ssrw10.jpg",
    "imgs": [
      "images/products/p435_0_ssrw10.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "84%",
    "condition": "جيد جدا"
  },
  {
    "id": 434,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "19000",
    "originalPrice": "19500",
    "description": "iPhone 13 \nGB: 128\nBi: 86%\nTax",
    "img": "images/products/p434_0_ssrw10.jpg",
    "imgs": [
      "images/products/p434_0_ssrw10.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": "ممتاز"
  },
  {
    "id": 433,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "29500",
    "description": "iPhone 13 \nGB: 128\nBi: 91%",
    "img": "images/products/p433_0_hbvivq.jpg",
    "imgs": [
      "images/products/p433_0_hbvivq.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "ممتاز"
  },
  {
    "id": 432,
    "cat": "used",
    "name": "Ipone 13 used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "17000",
    "originalPrice": "18000",
    "description": "iPhone 13 \nGB: 128\nBi: 76%\nTax",
    "img": "images/products/p432_0_gl68s4.jpg",
    "imgs": [
      "images/products/p432_0_gl68s4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76%",
    "condition": "جيد"
  },
  {
    "id": 431,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "24000",
    "originalPrice": "24500",
    "description": "iPhone 13 \nGB: 128\nBi: 86%\nباغه",
    "img": "images/products/p431_0_5a4pd1.jpg",
    "imgs": [
      "images/products/p431_0_5a4pd1.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": "جيد"
  },
  {
    "id": 430,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "",
    "price": "26000",
    "originalPrice": "26500",
    "description": "iPhone 13 \nGB: 128\nBi: 92%",
    "img": "images/products/p430_0_yjvix9.jpg",
    "imgs": [
      "images/products/p430_0_yjvix9.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "92%",
    "condition": "ممتاز"
  },
  {
    "id": 429,
    "cat": "used",
    "name": "Iphone 13 used u",
    "storage": "256",
    "color": "أحمر",
    "colorHex": "#dc2626",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "29500",
    "description": "iPhone 13 \nGB: 256\nBi: 84%",
    "img": "images/products/p429_0_lf87zc.jpg",
    "imgs": [
      "images/products/p429_0_lf87zc.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "84%",
    "condition": "جيد جدا"
  },
  {
    "id": 428,
    "cat": "used",
    "name": "Iphone 14 used u",
    "storage": "128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "29500",
    "description": "iPhone 14\nGB: 128\nBi: 86%",
    "img": "images/products/p428_0_azqp0v.jpg",
    "imgs": [
      "images/products/p428_0_azqp0v.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": "ممتاز"
  },
  {
    "id": 427,
    "cat": "used",
    "name": "Iphone 14 used u",
    "storage": "128",
    "color": "أحمر",
    "colorHex": "#dc2626",
    "brand": "Apple",
    "price": "28000",
    "originalPrice": "29000",
    "description": "iPhone 14 \nGB: 128\nBi: 84%",
    "img": "images/products/p427_0_lmsld3.jpg",
    "imgs": [
      "images/products/p427_0_lmsld3.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "84%",
    "condition": "ممتاز"
  },
  {
    "id": 426,
    "cat": "used",
    "name": "15used u",
    "storage": "128",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "38000",
    "originalPrice": "39000",
    "description": "iPhone 15 \nGB: 128\nBi: 89%",
    "img": "images/products/p426_0_hepsp6.jpg",
    "imgs": [
      "images/products/p426_0_hepsp6.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "89%",
    "condition": "ممتاز"
  },
  {
    "id": 425,
    "cat": "used",
    "name": "11pro used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "12000",
    "originalPrice": "13000",
    "description": "iPhone 11 Pro \nGB: 256\nBi: 74% \nScreen \nظهر \n12000",
    "img": "images/products/p425_0_78r780.jpg",
    "imgs": [
      "images/products/p425_0_78r780.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "74%",
    "condition": "جيد"
  },
  {
    "id": 424,
    "cat": "used",
    "name": "11pro used u",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "16000",
    "originalPrice": "165000",
    "description": "iPhone 11 Pro \nGB: 256\nBi: 71%\nN",
    "img": "images/products/p424_0_jrut91.jpg",
    "imgs": [
      "images/products/p424_0_jrut91.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "71%",
    "condition": "جيد جدا"
  },
  {
    "id": 423,
    "cat": "used",
    "name": "11pro used u",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "16000",
    "originalPrice": "16500",
    "description": "iPhone 11 Pro \nGB: 256\nBi: 74% \n16000",
    "img": "images/products/p423_0_7yy246.jpg",
    "imgs": [
      "images/products/p423_0_7yy246.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "74%",
    "condition": "جيد"
  },
  {
    "id": 422,
    "cat": "used",
    "name": "12pro used u",
    "storage": "128",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "Apple",
    "price": "16500",
    "originalPrice": "17000",
    "description": "iPhone 12 Pro \nGB: 128\nBi: 91% \nظهر \nBattery \n16500",
    "img": "images/products/p422_0_mgxgj2.jpg",
    "imgs": [
      "images/products/p422_0_mgxgj2.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "جيد"
  },
  {
    "id": 421,
    "cat": "used",
    "name": "12pro used u",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "18000",
    "originalPrice": "19000",
    "description": "iPhone 12 Pro \nGB: 256\nBi: 81%\nUsed screen\nظهر",
    "img": "images/products/p421_0_4on1nc.jpg",
    "imgs": [
      "images/products/p421_0_4on1nc.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "81%",
    "condition": "جيد"
  },
  {
    "id": 420,
    "cat": "used",
    "name": "13pro used u",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "25000",
    "originalPrice": "26000",
    "description": "iPhone 13 Pro \nGB: 256\nBi: 82%\nTax",
    "img": "images/products/p420_0_67ucli.jpg",
    "imgs": [
      "images/products/p420_0_67ucli.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "82%",
    "condition": "ممتاز"
  },
  {
    "id": 418,
    "cat": "used",
    "name": "11pro max used",
    "storage": "512",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "21000",
    "originalPrice": "22000",
    "description": "11pro max \n512\n84%\nWith box\nNo tax",
    "img": "images/products/p418_0_w6l4o1.jpg",
    "imgs": [
      "images/products/p418_0_w6l4o1.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "84%",
    "condition": "ممتاز"
  },
  {
    "id": 416,
    "cat": "used",
    "name": "13pro max used z",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "39000",
    "originalPrice": "40000",
    "description": "13pro max \n256\n79%\nWith box \nNo tax",
    "img": "images/products/p416_0_acbw2i.jpg",
    "imgs": [
      "images/products/p416_0_acbw2i.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "79%",
    "condition": "ممتاز"
  },
  {
    "id": 412,
    "cat": "used",
    "name": "12pro max used z",
    "storage": "512",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "28000",
    "originalPrice": "29000",
    "description": "12pro max\n75%\n512 \nNo box \n28000",
    "img": "images/products/p412_0_vj16un.jpg",
    "imgs": [
      "images/products/p412_0_vj16un.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "75%",
    "condition": "ممتاز"
  },
  {
    "id": 411,
    "cat": "used",
    "name": "15pro used u",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "38000",
    "originalPrice": "39000",
    "description": "iPhone 15 Pro \nGB: 256\nBi: 81%\nظهر",
    "img": "images/products/p411_0_xrcmxg.jpg",
    "imgs": [
      "images/products/p411_0_xrcmxg.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "81%",
    "condition": "جيد"
  },
  {
    "id": 406,
    "cat": "used",
    "name": "14plus used u",
    "storage": "256",
    "color": "وردي",
    "colorHex": "#f9a8d4",
    "brand": "Apple",
    "price": "24000",
    "originalPrice": "25000",
    "description": "iPhone 14 Plus \nGB: 256\nBi: 88%\nLine",
    "img": "images/products/p406_0_25924v.jpg",
    "imgs": [
      "images/products/p406_0_25924v.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "88%",
    "condition": "جيد"
  },
  {
    "id": 404,
    "cat": "used",
    "name": "16pro used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "55000",
    "originalPrice": "56000",
    "description": "iPhone 16 Pro \nGB: 256\nBi: 89%\n55000",
    "img": "images/products/p404_0_ju8sdw.jpg",
    "imgs": [
      "images/products/p404_0_ju8sdw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "89%",
    "condition": "ممتاز"
  },
  {
    "id": 403,
    "cat": "used",
    "name": "16plus used u",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "35000",
    "originalPrice": "36000",
    "description": "iPhone 16 Plus \nGB: 128\nBi: 100% \n(101🔌)\nTax",
    "img": "images/products/p403_0_s1pxlh.jpg",
    "imgs": [
      "images/products/p403_0_s1pxlh.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 402,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "256",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "Apple",
    "price": "25000",
    "originalPrice": "25500",
    "description": "iPhone 12 Pro Max \nGB: 256 \nBi: 76%",
    "img": "images/products/p402_0_rbwkr2.jpg",
    "imgs": [
      "images/products/p402_0_rbwkr2.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76%",
    "condition": "جيد"
  },
  {
    "id": 401,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "256",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "Apple",
    "price": "26000",
    "originalPrice": "27000",
    "description": "iPhone 12 Pro Max\nGB: 256\nBi: 86%",
    "img": "images/products/p401_0_s4hxv2.jpg",
    "imgs": [
      "images/products/p401_0_s4hxv2.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": "جيد جدا"
  },
  {
    "id": 400,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "512",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "Apple",
    "price": "27000",
    "originalPrice": "28000",
    "description": "iPhone12 Pro Max\nGB: 512\nBi: 74%",
    "img": "images/products/p400_0_i6s7vl.jpg",
    "imgs": [
      "images/products/p400_0_i6s7vl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "74%",
    "condition": "جيد"
  },
  {
    "id": 399,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "28000",
    "originalPrice": "29000",
    "description": "iPhone 12 Pro Max\nGB: 256\nBi: 87%",
    "img": "images/products/p399_0_42jzy.jpg",
    "imgs": [
      "images/products/p399_0_42jzy.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "87%",
    "condition": "جيد"
  },
  {
    "id": 398,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "26000",
    "originalPrice": "27000",
    "description": "iPhone 12 Pro Max\nGB: 256\nBi: 81%",
    "img": "images/products/p398_0_q82k2c.jpg",
    "imgs": [
      "images/products/p398_0_q82k2c.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "81%",
    "condition": "جيد"
  },
  {
    "id": 397,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "25500",
    "originalPrice": "26000",
    "description": "iPhone 12 Pro Max \nGB: 256\nBi :81%\n2Sim\nظهر",
    "img": "images/products/p397_0_59vpez.jpg",
    "imgs": [
      "images/products/p397_0_59vpez.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "81%",
    "condition": "جيد"
  },
  {
    "id": 396,
    "cat": "used",
    "name": "13pro max used u",
    "storage": "512",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "38000",
    "originalPrice": "39000",
    "description": "iPhone 13 Pro Max \nGB: 512\nBi: 76%",
    "img": "images/products/p396_0_vufzmt.jpg",
    "imgs": [
      "images/products/p396_0_vufzmt.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76%",
    "condition": "جيد"
  },
  {
    "id": 395,
    "cat": "used",
    "name": "13pro max used u",
    "storage": "1TB",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "41000",
    "originalPrice": "42000",
    "description": "iPhone 13 Pro Max\nGB: 1 TB\nBi: 85% \nظهر",
    "img": "images/products/p395_0_pni53w.jpg",
    "imgs": [
      "images/products/p395_0_pni53w.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "85%",
    "condition": "جيد"
  },
  {
    "id": 393,
    "cat": "used",
    "name": "13pro max used u",
    "storage": "",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "",
    "price": "40000",
    "originalPrice": "41000",
    "description": "iPhone 13 Pro Max \nGB :512\nBi: 79%",
    "img": "images/products/p393_0_q4gqvm.jpg",
    "imgs": [
      "images/products/p393_0_q4gqvm.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "79%",
    "condition": "ممتاز"
  },
  {
    "id": 392,
    "cat": "used",
    "name": "13pro max used u",
    "storage": "128",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "Apple",
    "price": "24000",
    "originalPrice": "25000",
    "description": "iPhone 13 Pro Max \nGB: 128\nBi: 77% \nTax",
    "img": "images/products/p392_0_6vlbbt.jpg",
    "imgs": [
      "images/products/p392_0_6vlbbt.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "77%",
    "condition": "ممتاز"
  },
  {
    "id": 390,
    "cat": "used",
    "name": "17pro max used s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "91000",
    "originalPrice": "92000",
    "description": "17pro max\n256\n100%\n85cycle\nNo tax",
    "img": "images/products/p390_0_kvkwwz.jpg",
    "imgs": [
      "images/products/p390_0_kvkwwz.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 389,
    "cat": "used",
    "name": "17Air used s",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "52000",
    "originalPrice": "53000",
    "description": "17air\n256\n100%\n15cycle\nNo tax",
    "img": "images/products/p389_0_5yghh0.jpg",
    "imgs": [
      "images/products/p389_0_5yghh0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 387,
    "cat": "used",
    "name": "16pro max used s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "66000",
    "originalPrice": "67000",
    "description": "16pro max \n256\n91%\nNo tax",
    "img": "images/products/p387_0_11mxrb.jpg",
    "imgs": [
      "images/products/p387_0_11mxrb.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "ممتاز"
  },
  {
    "id": 386,
    "cat": "used",
    "name": "12Pro Max used u",
    "storage": "128",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "Apple",
    "price": "26000",
    "originalPrice": "27000",
    "description": "iPhone 12 Pro Max\nGB :128\nBi: 79%",
    "img": "images/products/p386_0_5et6pi.jpg",
    "imgs": [
      "images/products/p386_0_5et6pi.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "79%",
    "condition": "جيد"
  },
  {
    "id": 385,
    "cat": "used",
    "name": "17pro max used  z",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "91000",
    "originalPrice": "92000",
    "description": "17pro max \n256\n100%\n30cycle",
    "img": "images/products/p385_0_p4x5kw.jpg",
    "imgs": [
      "images/products/p385_0_p4x5kw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 384,
    "cat": "used",
    "name": "14pro max used u",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "30000",
    "originalPrice": "31000",
    "description": "iPhone 14 Pro Max\nGB: 256\nBi: 83%\nTax",
    "img": "images/products/p384_0_w7i6j9.jpg",
    "imgs": [
      "images/products/p384_0_w7i6j9.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "83%",
    "condition": "ممتاز"
  },
  {
    "id": 383,
    "cat": "used",
    "name": "14pro max used u",
    "storage": "256",
    "color": "Deep Purple",
    "colorHex": "#5e548e",
    "brand": "Apple",
    "price": "44000",
    "originalPrice": "45000",
    "description": "iPhone 14 Pro Max\nGB: 256\nBi: 81%",
    "img": "images/products/p383_0_kofsh0.jpg",
    "imgs": [
      "images/products/p383_0_kofsh0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "81%",
    "condition": "ممتاز"
  },
  {
    "id": 381,
    "cat": "used",
    "name": "14pro max used u",
    "storage": "256",
    "color": "Deep Purple",
    "colorHex": "#5e548e",
    "brand": "Apple",
    "price": "39000",
    "originalPrice": "40000",
    "description": "iPhone 14 Pro Max\nGB: 256\nBi: 76%",
    "img": "images/products/p381_0_cw1qme.jpg",
    "imgs": [
      "images/products/p381_0_cw1qme.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76%",
    "condition": "جيد"
  },
  {
    "id": 380,
    "cat": "used",
    "name": "14pro max used u",
    "storage": "512",
    "color": "Deep Purple",
    "colorHex": "#5e548e",
    "brand": "Apple",
    "price": "46000",
    "originalPrice": "47000",
    "description": "iPhone 14 Pro Max\nGB: 512\nBi: 87%",
    "img": "images/products/p380_0_cw1qme.jpg",
    "imgs": [
      "images/products/p380_0_cw1qme.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "87%",
    "condition": "ممتاز"
  },
  {
    "id": 378,
    "cat": "used",
    "name": "15pro max used u",
    "storage": "",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "50000",
    "originalPrice": "51000",
    "description": "iPhone 15 Pro Max\nGB: 256\nBi: 86%",
    "img": "images/products/p378_0_irsrpy.jpg",
    "imgs": [
      "images/products/p378_0_irsrpy.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": ".ممتاز"
  },
  {
    "id": 377,
    "cat": "used",
    "name": "15pro max used u",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "51000",
    "originalPrice": "52000",
    "description": "iPhone 15 Pro Max \nGB: 256\nBi: 89%",
    "img": "images/products/p377_0_irsrpy.jpg",
    "imgs": [
      "images/products/p377_0_irsrpy.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "89%",
    "condition": "ممتاز"
  },
  {
    "id": 376,
    "cat": "used",
    "name": "15pro max used U",
    "storage": "256",
    "color": "Titanium",
    "colorHex": "#8e8e93",
    "brand": "Apple",
    "price": "49000",
    "originalPrice": "50000",
    "description": "iPhone 15 Pro Max\nGB: 256\nBi: 86%",
    "img": "images/products/p376_0_qolh16.jpg",
    "imgs": [
      "images/products/p376_0_qolh16.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": "جيد"
  },
  {
    "id": 375,
    "cat": "used",
    "name": "15pro max used U",
    "storage": "",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "50000",
    "originalPrice": "51000",
    "description": "iPhone 15 Pro Max\nGB: 256\nBi: 86%\n2Sim",
    "img": "images/products/p375_0_t47sr2.jpg",
    "imgs": [
      "images/products/p375_0_t47sr2.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86%",
    "condition": "جيد"
  },
  {
    "id": 374,
    "cat": "used",
    "name": "15pro max used U",
    "storage": "512",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "55000",
    "originalPrice": "56000",
    "description": "iPhone 15 Pro Max \nGB: 512\nBi: 87%",
    "img": "images/products/p374_0_qzoh9x.jpg",
    "imgs": [
      "images/products/p374_0_qzoh9x.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "87%",
    "condition": "ممتاز"
  },
  {
    "id": 372,
    "cat": "used",
    "name": "iphone 17 promax 256 used U",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "64000",
    "originalPrice": "65000",
    "description": "iPhone 17 Pro Max\nGB: 256\nBi: 100%\n(30🔌)\nTax",
    "img": "images/products/p372_0_qgov00.jpg",
    "imgs": [
      "images/products/p372_0_qgov00.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 371,
    "cat": "used",
    "name": "Iphone 17 pro max 512 used  U",
    "storage": "512",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "73000",
    "originalPrice": "74000",
    "description": "iPhone 17 Pro Max\nGB: 512\nBi: 100%\n(6🔌)\nTax",
    "img": "images/products/p371_0_gxag6n.jpg",
    "imgs": [
      "images/products/p371_0_gxag6n.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100%",
    "condition": "ممتاز"
  },
  {
    "id": 368,
    "cat": "new",
    "name": "Iphone 17 pro max 256 blue",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "apple",
    "price": "63500",
    "originalPrice": "66000",
    "description": "With tax\nEsim",
    "img": "images/products/p368_0_wr1xo8.jpg",
    "imgs": [
      "images/products/p368_0_wr1xo8.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 367,
    "cat": "new",
    "name": "17pro max 256 silver",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "apple",
    "price": "63500",
    "originalPrice": "66000",
    "description": "With tax\nESIM",
    "img": "images/products/p367_0_9ztq2i.jpg",
    "imgs": [
      "images/products/p367_0_9ztq2i.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 366,
    "cat": "new",
    "name": "iphone 17 promax 256 orange",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "apple",
    "price": "63500",
    "originalPrice": "66000",
    "description": "With Tax\nEsim",
    "img": "images/products/p366_0_v1dvpl.jpg",
    "imgs": [
      "images/products/p366_0_v1dvpl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 364,
    "cat": "used",
    "name": "13",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "30000",
    "description": "13used\n128GB\nNo box\nNo tax",
    "img": "images/products/p364_0_g2gav1.jpg",
    "imgs": [
      "images/products/p364_0_g2gav1.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "90",
    "condition": "ممتاز"
  },
  {
    "id": 362,
    "cat": "used",
    "name": "13",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "30000",
    "description": "13used\n128GB\nWith box\nNo tax",
    "img": "images/products/p362_0_abknxa.jpg",
    "imgs": [
      "images/products/p362_0_abknxa.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "88",
    "condition": "جيد جدا"
  },
  {
    "id": 361,
    "cat": "used",
    "name": "13",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "27000",
    "originalPrice": "28000",
    "description": "13used\n128GB\n1cycle\nWith box\nYes tax",
    "img": "images/products/p361_0_89i5k6.jpg",
    "imgs": [
      "images/products/p361_0_89i5k6.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 357,
    "cat": "used",
    "name": "Honor 400 5g",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Honor",
    "price": "12500",
    "originalPrice": "13900",
    "description": "Honor 400 5g\nRam:8\nGB:256\nWith Box\nNo Tax",
    "img": "images/products/p357_0_oc4yzm.jpg",
    "imgs": [
      "images/products/p357_0_oc4yzm.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 350,
    "cat": "used",
    "name": "Honor X9c 5g",
    "storage": "256",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Honor",
    "price": "16000",
    "originalPrice": "17000",
    "description": "Honor X9c 5g\nRam:12\nGB:256\nWith Box\nNo Tax",
    "img": "images/products/p350_0_51hdlm.jpg",
    "imgs": [
      "images/products/p350_0_51hdlm.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 349,
    "cat": "used",
    "name": "Honor X9d 5g",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Honor",
    "price": "17500",
    "originalPrice": "18500",
    "description": "Honor X9d 5g \nRam:12\nGB:256\nWith Box\nNo Tax",
    "img": "images/products/p349_0_ius7wm.jpg",
    "imgs": [
      "images/products/p349_0_ius7wm.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 344,
    "cat": "used",
    "name": "Reno11f 5g",
    "storage": "256",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Oppo",
    "price": "12500",
    "originalPrice": "13500",
    "description": "Oppo Reno 11f 5g\nRam:8\nGB:256\nWith Box\nNo Tax",
    "img": "images/products/p344_0_nap0tw.jpg",
    "imgs": [
      "images/products/p344_0_nap0tw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "جيد جدا"
  },
  {
    "id": 340,
    "cat": "used",
    "name": "Honor x8b",
    "storage": "512",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Honor",
    "price": "17500",
    "originalPrice": "18300",
    "description": "Honor x8b\nRam:8\nGB:512\nWith Box\nNo Tax",
    "img": "images/products/p340_0_4iwpvu.jpg",
    "imgs": [
      "images/products/p340_0_4iwpvu.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "جيد جدا"
  },
  {
    "id": 337,
    "cat": "used",
    "name": "16Pro max used",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "63000",
    "originalPrice": "65000",
    "description": "16pro max used\n256Gb\nWith box\nNo tax",
    "img": "images/products/p337_0_ghv5i.jpg",
    "imgs": [
      "images/products/p337_0_ghv5i.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "92",
    "condition": "جيد جدا"
  },
  {
    "id": 330,
    "cat": "used",
    "name": "16Pro Max",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "60000",
    "originalPrice": "61000",
    "description": "16Pro max used\n256Gb\nWith box\nNo tax",
    "img": "images/products/p330_0_a5hoyz.jpg",
    "imgs": [
      "images/products/p330_0_a5hoyz.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "94",
    "condition": "جيد جدا"
  },
  {
    "id": 329,
    "cat": "used",
    "name": "11",
    "storage": "128",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "14500",
    "originalPrice": "15500",
    "description": "11used\n128GB\nWith box\nNo tax",
    "img": "images/products/p329_0_pmv365.jpg",
    "imgs": [
      "images/products/p329_0_pmv365.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76",
    "condition": "جيد"
  },
  {
    "id": 328,
    "cat": "used",
    "name": "13",
    "storage": "128",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "30000",
    "description": "13used\n128GB\nWith box\nNo tax",
    "img": "images/products/p328_0_4qec4x.jpg",
    "imgs": [
      "images/products/p328_0_4qec4x.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "88",
    "condition": "جيد جدا"
  },
  {
    "id": 327,
    "cat": "used",
    "name": "14",
    "storage": "128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "37000",
    "originalPrice": "38000",
    "description": "14used\n128GB\nWith box\nNo tax",
    "img": "images/products/p327_0_kbokcr.jpg",
    "imgs": [
      "images/products/p327_0_kbokcr.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86",
    "condition": "جيد جدا"
  },
  {
    "id": 326,
    "cat": "used",
    "name": "14",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "31500",
    "originalPrice": "32500",
    "description": "14used\n128GB\nWith box\nNo tax",
    "img": "images/products/p326_0_k7non9.jpg",
    "imgs": [
      "images/products/p326_0_k7non9.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "78",
    "condition": "جيد"
  },
  {
    "id": 325,
    "cat": "used",
    "name": "Xs Max",
    "storage": "512",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "15000",
    "originalPrice": "16000",
    "description": "Xs Max used\n512GB\nWith box\nNo tax",
    "img": "images/products/p325_0_bxfk18.jpg",
    "imgs": [
      "images/products/p325_0_bxfk18.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "77",
    "condition": "ممتاز"
  },
  {
    "id": 324,
    "cat": "used",
    "name": "13",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "18000",
    "originalPrice": "20000",
    "description": "13used\n128GB\nNO box\n tax",
    "img": "images/products/p324_0_yd0u4m.jpg",
    "imgs": [
      "images/products/p324_0_yd0u4m.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86",
    "condition": "ممتاز"
  },
  {
    "id": 323,
    "cat": "used",
    "name": "13",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "32000",
    "description": "13used\n128GB\nWarranty 1 Year\nWith box\nNo tax",
    "img": "images/products/p323_0_iahlxd.jpg",
    "imgs": [
      "images/products/p323_0_iahlxd.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "95",
    "condition": "ممتاز"
  },
  {
    "id": 322,
    "cat": "used",
    "name": "Iphone 14plus used s",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "31000",
    "originalPrice": "33000",
    "description": "14Plus used\n128GB\nWith box\nNo tax",
    "img": "images/products/p322_0_uwax76.jpg",
    "imgs": [
      "images/products/p322_0_uwax76.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91",
    "condition": "ممتاز"
  },
  {
    "id": 321,
    "cat": "used",
    "name": "16",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "50000",
    "originalPrice": "52500",
    "description": "16\n128GB\n155Cycle\nWith box\nNo tax",
    "img": "images/products/p321_0_sovvc.jpg",
    "imgs": [
      "images/products/p321_0_sovvc.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 320,
    "cat": "used",
    "name": "12Pro Max used s",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "26000",
    "originalPrice": "27000",
    "description": "12Pro max used\n256Gb\nNo box\nNo tax",
    "img": "images/products/p320_0_k7zo91.jpg",
    "imgs": [
      "images/products/p320_0_k7zo91.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "76",
    "condition": "جيد"
  },
  {
    "id": 319,
    "cat": "used",
    "name": "13pro max used s",
    "storage": "256",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "35000",
    "originalPrice": "37000",
    "description": "15pro max used\n256Gb\nNo box\nNo tax",
    "img": "images/products/p319_0_8herrq.jpg",
    "imgs": [
      "images/products/p319_0_8herrq.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "79",
    "condition": "جيد جدا"
  },
  {
    "id": 317,
    "cat": "used",
    "name": "15pro max used s",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "50000",
    "originalPrice": "51500",
    "description": "15pro max used\n256Gb\nNo box\nNo tax",
    "img": "images/products/p317_0_tw96a8.jpg",
    "imgs": [
      "images/products/p317_0_tw96a8.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "88",
    "condition": "جيد جدا"
  },
  {
    "id": 309,
    "cat": "used",
    "name": "Iphone 15 used k",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "32000",
    "originalPrice": "35000",
    "description": "Iphone 15 \n128\n83%\nWith box\nNo tax",
    "img": "images/products/p309_0_p1aev5.jpg",
    "imgs": [
      "images/products/p309_0_p1aev5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "82%",
    "condition": "جيد"
  },
  {
    "id": 305,
    "cat": "used",
    "name": "13pro max used k",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "37000",
    "originalPrice": "39000",
    "description": "13pro max used\n256G\n77%\nNo Box \nNo Tax",
    "img": "images/products/p305_0_8kwwy5.jpg",
    "imgs": [
      "images/products/p305_0_8kwwy5.jpg",
      "images/products/p305_1_gqhpki.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "77%",
    "condition": "ممتاز"
  },
  {
    "id": 304,
    "cat": "used",
    "name": "13pro max used k",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "39000",
    "originalPrice": "40000",
    "description": "13promax used\n256G\n83%\nNo Box\nNo Tax",
    "img": "images/products/p304_0_6b7801.jpg",
    "imgs": [
      "images/products/p304_0_6b7801.jpg",
      "images/products/p304_1_gmor24.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "79%",
    "condition": "ممتاز"
  },
  {
    "id": 301,
    "cat": "used",
    "name": "16pro max used k",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "59000",
    "originalPrice": "63000",
    "description": "16pro max used\n256G\n91%\nZa\nWith Box\nNo Tax",
    "img": "images/products/p301_0_1sv9ii.jpg",
    "imgs": [
      "images/products/p301_0_1sv9ii.jpg",
      "images/products/p301_1_qei9gh.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91%",
    "condition": "ممتاز"
  },
  {
    "id": 280,
    "cat": "new",
    "name": "oppo a6x  4/64 blue",
    "storage": "4/64 blue",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "oppo",
    "price": "8100",
    "originalPrice": "8200",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6x 4G والذي يأتي لينافس في الفئة الاقتصادية بمعالج من نوع Snapdragon 685 ليقدم تجربة تصفح جيدة مع شاشة كبيرة بمساحة 6.75 بوصة مع دعم معدل التحديث الـ 120 هرتز بالأضافة لبطارية كبيرة السعة 6500 مللي أمبير .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6x 4G وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي .",
    "img": "images/products/p280_0_bstrs0.jpg",
    "imgs": [
      "images/products/p280_0_bstrs0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 279,
    "cat": "new",
    "name": "oppo a6x 4/64 iceblue",
    "storage": "4/64 iceblue",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "oppo",
    "price": "8100",
    "originalPrice": "8200",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6x 4G والذي يأتي لينافس في الفئة الاقتصادية بمعالج من نوع Snapdragon 685 ليقدم تجربة تصفح جيدة مع شاشة كبيرة بمساحة 6.75 بوصة مع دعم معدل التحديث الـ 120 هرتز بالأضافة لبطارية كبيرة السعة 6500 مللي أمبير .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6x 4G وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي .",
    "img": "images/products/p279_0_bamq92.jpg",
    "imgs": [
      "images/products/p279_0_bamq92.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 278,
    "cat": "new",
    "name": "oppo a6x 4/128 blue",
    "storage": "4/128 blue",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "oppo",
    "price": "9400",
    "originalPrice": "9900",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6x 4G والذي يأتي لينافس في الفئة الاقتصادية بمعالج من نوع Snapdragon 685 ليقدم تجربة تصفح جيدة مع شاشة كبيرة بمساحة 6.75 بوصة مع دعم معدل التحديث الـ 120 هرتز بالأضافة لبطارية كبيرة السعة 6500 مللي أمبير .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6x 4G وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي .",
    "img": "images/products/p278_0_bstrs0.jpg",
    "imgs": [
      "images/products/p278_0_bstrs0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 277,
    "cat": "new",
    "name": "oppo a6x 4/128",
    "storage": "4/128 iceblue",
    "color": "وردي",
    "colorHex": "#f9a8d4",
    "brand": "oppo",
    "price": "9400",
    "originalPrice": "9900",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6x 4G والذي يأتي لينافس في الفئة الاقتصادية بمعالج من نوع Snapdragon 685 ليقدم تجربة تصفح جيدة مع شاشة كبيرة بمساحة 6.75 بوصة مع دعم معدل التحديث الـ 120 هرتز بالأضافة لبطارية كبيرة السعة 6500 مللي أمبير .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6x 4G وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي .",
    "img": "images/products/p277_0_bamq92.jpg",
    "imgs": [
      "images/products/p277_0_bamq92.jpg"
    ],
    "featured": false,
    "variants": [
      {
        "color": "",
        "colorHex": "#0A0A0A",
        "price": "",
        "originalPrice": "",
        "imgs": []
      }
    ],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 276,
    "cat": "new",
    "name": "oppo a6 4/128 blue",
    "storage": "4/128 blue",
    "color": "Sierra Blue",
    "colorHex": "#4a6fa5",
    "brand": "oppo",
    "price": "9700",
    "originalPrice": "10200",
    "description": "أعلنت شركة أوبو عن هاتفها الأحدث الـ Oppo A6 4G والذي يأتي لينافس في الفئة الاقتصادية بأعلى مقاومة للماء والغبار بمعيار IP68/IP69 مع شاشة من نوع IPS LCD بدقة متواضعة HD+ مع دعم معدل التحديث الـ 120 هرتز مع كاميرا خلفية 50 ميجا بكسل وسيلفي 8 ميجا بكسل مع استخدام معالج اقتصادي من كوالكم Snapdragon 685 بالأضافة لبطارية ضخمة بسعة 7000 مللي أمبير تدعم الشحن السريع بقوة 45 واط .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6 جيل رابع وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي فيما يلي .",
    "img": "images/products/p276_0_kqkaml.jpg",
    "imgs": [
      "images/products/p276_0_kqkaml.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 275,
    "cat": "new",
    "name": "oppo a6 4/128 gold",
    "storage": "4/128 gold",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "oppo",
    "price": "9700",
    "originalPrice": "10200",
    "description": "أعلنت شركة أوبو عن هاتفها الأحدث الـ Oppo A6 4G والذي يأتي لينافس في الفئة الاقتصادية بأعلى مقاومة للماء والغبار بمعيار IP68/IP69 مع شاشة من نوع IPS LCD بدقة متواضعة HD+ مع دعم معدل التحديث الـ 120 هرتز مع كاميرا خلفية 50 ميجا بكسل وسيلفي 8 ميجا بكسل مع استخدام معالج اقتصادي من كوالكم Snapdragon 685 بالأضافة لبطارية ضخمة بسعة 7000 مللي أمبير تدعم الشحن السريع بقوة 45 واط .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6 جيل رابع وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي فيما يلي .",
    "img": "images/products/p275_0_lnkvli.jpg",
    "imgs": [
      "images/products/p275_0_lnkvli.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 274,
    "cat": "new",
    "name": "oppo a6 6/128 blue",
    "storage": "6/128blue",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "oppo",
    "price": "12700",
    "originalPrice": "13000",
    "description": "أعلنت شركة أوبو عن هاتفها الأحدث الـ Oppo A6 4G والذي يأتي لينافس في الفئة الاقتصادية بأعلى مقاومة للماء والغبار بمعيار IP68/IP69 مع شاشة من نوع IPS LCD بدقة متواضعة HD+ مع دعم معدل التحديث الـ 120 هرتز مع كاميرا خلفية 50 ميجا بكسل وسيلفي 8 ميجا بكسل مع استخدام معالج اقتصادي من كوالكم Snapdragon 685 بالأضافة لبطارية ضخمة بسعة 7000 مللي أمبير تدعم الشحن السريع بقوة 45 واط .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6 جيل رابع وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي فيما يلي .",
    "img": "images/products/p274_0_kqkaml.jpg",
    "imgs": [
      "images/products/p274_0_kqkaml.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 273,
    "cat": "new",
    "name": "oppo a6 6/128 gold",
    "storage": "6/128 gold",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "oppo",
    "price": "12700",
    "originalPrice": "13000",
    "description": "أعلنت شركة أوبو عن هاتفها الأحدث الـ Oppo A6 4G والذي يأتي لينافس في الفئة الاقتصادية بأعلى مقاومة للماء والغبار بمعيار IP68/IP69 مع شاشة من نوع IPS LCD بدقة متواضعة HD+ مع دعم معدل التحديث الـ 120 هرتز مع كاميرا خلفية 50 ميجا بكسل وسيلفي 8 ميجا بكسل مع استخدام معالج اقتصادي من كوالكم Snapdragon 685 بالأضافة لبطارية ضخمة بسعة 7000 مللي أمبير تدعم الشحن السريع بقوة 45 واط .. فدعونا نتعرف على المواصفات الكاملة لهاتف Oppo A6 جيل رابع وما هي أهم مميزاته وعيوبه وهل يستحق الشراء أم لا على النحو التالي فيما يلي .",
    "img": "images/products/p273_0_lnkvli.jpg",
    "imgs": [
      "images/products/p273_0_lnkvli.jpg"
    ],
    "featured": false,
    "variants": [
      {
        "color": "",
        "colorHex": "#0A0A0A",
        "price": "",
        "originalPrice": "",
        "imgs": []
      }
    ],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 272,
    "cat": "new",
    "name": "oppo a6 pro 4g 8/256 bink",
    "storage": "8/256 bink",
    "color": "وردي",
    "colorHex": "#f9a8d4",
    "brand": "oppo",
    "price": "15800",
    "originalPrice": "16000",
    "description": "يأتي هاتف Oppo A6 Pro 4G (وفقاً لأحدث البيانات) بمعالج MediaTek Helio G100 أو Snapdragon 680، مع ذاكرة تخزين 256 جيجابايت ورام 8 جيجابايت، وشاشة 6.5-6.7 بوصة (غالباً IPS LCD) بتردد 90 هرتز. يتميز ببطارية ضخمة تصل إلى 7000 مللي أمبير (في بعض الإصدارات) أو 5000 مللي أمبير مع شحن سريع 45-80 واط، وكاميرا خلفية أساسية بدقة 50 ميجابكسل",
    "img": "images/products/p272_0_y2ir6y.jpg",
    "imgs": [
      "images/products/p272_0_y2ir6y.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 271,
    "cat": "new",
    "name": "oppo a6 pro 4g 8/256 blue",
    "storage": "8/256 blue",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "oppo",
    "price": "15800",
    "originalPrice": "16000",
    "description": "يأتي هاتف Oppo A6 Pro 4G (وفقاً لأحدث البيانات) بمعالج MediaTek Helio G100 أو Snapdragon 680، مع ذاكرة تخزين 256 جيجابايت ورام 8 جيجابايت، وشاشة 6.5-6.7 بوصة (غالباً IPS LCD) بتردد 90 هرتز. يتميز ببطارية ضخمة تصل إلى 7000 مللي أمبير (في بعض الإصدارات) أو 5000 مللي أمبير مع شحن سريع 45-80 واط، وكاميرا خلفية أساسية بدقة 50 ميجابكسل",
    "img": "images/products/p271_0_wvcdc1.jpg",
    "imgs": [
      "images/products/p271_0_wvcdc1.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 239,
    "cat": "new",
    "name": "samsung a57 12/256 volite",
    "storage": "256GB · volite",
    "color": "Deep Purple",
    "colorHex": "#5e548e",
    "brand": "",
    "price": "27500",
    "originalPrice": "31000",
    "description": "يأتي هاتف سامسونج Galaxy A57 5G (المتوقع لعام 2026) بتصميم زجاجي أنيق وشاشة 6.7 بوصة Super AMOLED 120Hz، ومعالج Exynos 1680 (4 نانومتر)، وكاميرا رئيسية 50 ميجابكسل مع مثبت بصري، وشحن 45 واط، متوفر بأربعة ألوان",
    "img": "images/products/p239_0_dbkzcr.jpg",
    "imgs": [
      "images/products/p239_0_dbkzcr.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 234,
    "cat": "new",
    "name": "ipad a16 128 wifi blue",
    "storage": "128GB · blue",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "apple",
    "price": "19700",
    "originalPrice": "21000",
    "description": "يتميز جهاز آيباد الجيل الحادي عشر (موديل 2025) بشريحة A16 Bionic القوية (4 نانومتر)، وشاشة Liquid Retina مقاس 10.9 أو 11 بوصة، وذاكرة رام 6 جيجابايت، مع كاميرات 12MP تدعم Center Stage، وبطارية تدوم لـ 10 ساعات، ويعد خياراً مثالياً للأداء السريع والسلس بأسعار معقولة",
    "img": "images/products/p234_0_dqy3hn.jpg",
    "imgs": [
      "images/products/p234_0_dqy3hn.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 233,
    "cat": "new",
    "name": "ipad a16 128 wifi silver",
    "storage": "128GB · silver",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "apple",
    "price": "19700",
    "originalPrice": "21000",
    "description": "يتميز جهاز آيباد الجيل الحادي عشر (موديل 2025) بشريحة A16 Bionic القوية (4 نانومتر)، وشاشة Liquid Retina مقاس 10.9 أو 11 بوصة، وذاكرة رام 6 جيجابايت، مع كاميرات 12MP تدعم Center Stage، وبطارية تدوم لـ 10 ساعات، ويعد خياراً مثالياً للأداء السريع والسلس بأسعار معقولة",
    "img": "images/products/p233_0_8qhjyl.jpg",
    "imgs": [
      "images/products/p233_0_8qhjyl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 232,
    "cat": "new",
    "name": "iPhone 16 (128) purple",
    "storage": "128GB purple",
    "color": "وردي",
    "colorHex": "#f9a8d4",
    "brand": "apple",
    "price": "54500",
    "originalPrice": "58000",
    "description": "بشاشة 6.1 بوصة، ومعالج A18 القوي (3 نانومتر)، ونظام كاميرا مزدوج 48MP، مع ذاكرة رام 8GB، وهيكل ألومنيوم مقاوم للماء (IP68) وزجاج خلفي ملون، بالإضافة إلى زر التحكم بالكاميرا الجديد",
    "img": "images/products/p232_0_ye2y16.jpg",
    "imgs": [
      "images/products/p232_0_ye2y16.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 231,
    "cat": "new",
    "name": "iPhone 16 (128) green",
    "storage": "128GB · Green",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "apple",
    "price": "54500",
    "originalPrice": "58000",
    "description": "بشاشة OLED مقاس 6.1 بوصة، ومعالج A18 الجديد بتقنية 3 نانومتر، وذاكرة وصول عشوائي 8 جيجابايت لدعم الذكاء الاصطناعي. يأتي الهاتف بكاميرا أساسية 48 ميجابكسل، وزر \"التحكم في الكاميرا\" الجديد، وهيكل مقاوم للماء والغبار. كما يدعم شبكات 5G وبطارية محسّنة تدوم طوال اليوم",
    "img": "images/products/p231_0_lhoabn.jpg",
    "imgs": [
      "images/products/p231_0_lhoabn.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 230,
    "cat": "new",
    "name": "iPhone 16 128Gb  black",
    "storage": "128GB · black",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "apple",
    "price": "54500",
    "originalPrice": "58000",
    "description": "بشاشة OLED مقاس 6.1 بوصة، ومعالج A18 الجديد بتقنية 3 نانومتر، وذاكرة وصول عشوائي 8 جيجابايت لدعم الذكاء الاصطناعي. يأتي الهاتف بكاميرا أساسية 48 ميجابكسل، وزر \"التحكم في الكاميرا\" الجديد، وهيكل مقاوم للماء والغبار. كما يدعم شبكات 5G وبطارية محسّنة تدوم طوال اليوم",
    "img": "images/products/p230_0_mt9upw.jpg",
    "imgs": [
      "images/products/p230_0_mt9upw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 229,
    "cat": "new",
    "name": "iPhone 17 (256GB) blue",
    "storage": "256GB",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "apple",
    "price": "67000",
    "originalPrice": "69000",
    "description": "يأتي آيفون 17 (iPhone 17) بشاشة 6.3 بوصة من نوع LTPO OLED بتردد 120 هرتز لأول مرة في النسخة العادية، معالج A19 الجديد، كاميرا رئيسية وواسعة 48 ميجابكسل، وذاكرة عشوائية (RAM) أكبر لتحسين أداء الذكاء الاصطناعي، مما يجعله تحديثاً جوهرياً في الأداء والشاشة",
    "img": "images/products/p229_0_tm1is.jpg",
    "imgs": [
      "images/products/p229_0_tm1is.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 228,
    "cat": "new",
    "name": "iPhone 17 (256GB) green",
    "storage": "256GB",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "apple",
    "price": "67000",
    "originalPrice": "69000",
    "description": "يأتي آيفون 17 (iPhone 17) بشاشة 6.3 بوصة من نوع LTPO OLED بتردد 120 هرتز لأول مرة في النسخة العادية، معالج A19 الجديد، كاميرا رئيسية وواسعة 48 ميجابكسل، وذاكرة عشوائية (RAM) أكبر لتحسين أداء الذكاء الاصطناعي، مما يجعله تحديثاً جوهرياً في الأداء والشاشة.",
    "img": "images/products/p228_0_oini3g.jpg",
    "imgs": [
      "images/products/p228_0_oini3g.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 227,
    "cat": "new",
    "name": "iPhone 17 (256GB) black",
    "storage": "256GB · black",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "apple",
    "price": "66000",
    "originalPrice": "69000",
    "description": "يأتي آيفون 17 (iPhone 17) بشاشة 6.3 بوصة من نوع LTPO OLED بتردد 120 هرتز لأول مرة في النسخة العادية، معالج A19 الجديد، كاميرا رئيسية وواسعة 48 ميجابكسل، وذاكرة عشوائية (RAM) أكبر لتحسين أداء الذكاء الاصطناعي، مما يجعله تحديثاً جوهرياً في الأداء والشاشة.",
    "img": "images/products/p227_0_p3yuwk.jpg",
    "imgs": [
      "images/products/p227_0_p3yuwk.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 226,
    "cat": "new",
    "name": "iPhone 17 (256GB) white",
    "storage": "256GB ·",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "apple",
    "price": "66000",
    "originalPrice": "69000",
    "description": "يأتي آيفون 17 (iPhone 17) بشاشة 6.3 بوصة من نوع LTPO OLED بتردد 120 هرتز لأول مرة في النسخة العادية، معالج A19 الجديد، كاميرا رئيسية وواسعة 48 ميجابكسل، وذاكرة عشوائية (RAM) أكبر لتحسين أداء الذكاء الاصطناعي، مما يجعله تحديثاً جوهرياً في الأداء والشاشة",
    "img": "images/products/p226_0_okq78k.jpg",
    "imgs": [
      "images/products/p226_0_okq78k.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 225,
    "cat": "new",
    "name": "iphone 17 pro256 blue",
    "storage": "256GB ·blue",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "apple",
    "price": "95000",
    "originalPrice": "101000",
    "description": "يأتي آيفون 17 برو (iPhone 17 Pro) بشاشة 6.3 بوصة من نوع LTPO OLED، ومعالج A19 Pro بتقنية 3 نانو، مع ذاكرة عشوائية 12 جيجابايت، ونظام كاميرات خلفية ثلاثية بدقة 48 ميجابكسل، بالإضافة إلى إطار من الألومنيوم، ودعم لشبكات Wi-Fi 7",
    "img": "images/products/p225_0_mzk330.jpg",
    "imgs": [
      "images/products/p225_0_mzk330.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 224,
    "cat": "new",
    "name": "iphone 17 pro256 silver",
    "storage": "silver.256GB",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "apple",
    "price": "95000",
    "originalPrice": "100000",
    "description": "يأتي آيفون 17 برو (iPhone 17 Pro) بشاشة 6.3 بوصة من نوع LTPO OLED، ومعالج A19 Pro بتقنية 3 نانو، مع ذاكرة عشوائية 12 جيجابايت، ونظام كاميرات خلفية ثلاثية بدقة 48 ميجابكسل، بالإضافة إلى إطار من الألومنيوم، ودعم لشبكات Wi-Fi 7",
    "img": "images/products/p224_0_onnnxx.jpg",
    "imgs": [
      "images/products/p224_0_onnnxx.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": false,
    "battery": "",
    "condition": ""
  },
  {
    "id": 223,
    "cat": "new",
    "name": "iphone 17 pro256 orange",
    "storage": "256GB · orange",
    "color": "اورنجh,h,vk[vk[",
    "colorHex": "#f5a700",
    "brand": "apple",
    "price": "85000",
    "originalPrice": "90000",
    "description": "يأتي آيفون 17 برو (iPhone 17 Pro) بشاشة 6.3 بوصة من نوع LTPO OLED، ومعالج A19 Pro بتقنية 3 نانو، مع ذاكرة عشوائية 12 جيجابايت، ونظام كاميرات خلفية ثلاثية بدقة 48 ميجابكسل، بالإضافة إلى إطار من الألومنيوم، ودعم لشبكات Wi-Fi 7",
    "img": "images/products/p223_0_b5vrzj.jpg",
    "imgs": [
      "images/products/p223_0_b5vrzj.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 222,
    "cat": "new",
    "name": "iphone 17 promax 256 blue",
    "storage": "blue-256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "apple",
    "price": "96500",
    "originalPrice": "110000",
    "description": "يتميز آيفون 17 برو ماكس (iPhone 17 Pro Max) بشاشة ضخمة 6.9 بوصة من نوع LTPO OLED، ومعالج Apple A19 Pro (3 نانومتر)، وذاكرة عشوائية تصل إلى 12 جيجابايت، مع كاميرات خلفية بدقة 48 ميجابكسل، وبطارية بسعة 4823 مللي أمب",
    "img": "images/products/p222_0_xt1ecs.jpg",
    "imgs": [
      "images/products/p222_0_xt1ecs.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 221,
    "cat": "new",
    "name": "iphone 17 pro max256 silver",
    "storage": "256GB-SILVER",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "apple",
    "price": "96500",
    "originalPrice": "110000",
    "description": "يتميز آيفون 17 برو ماكس (iPhone 17 Pro Max) بشاشة ضخمة 6.9 بوصة من نوع LTPO OLED، ومعالج Apple A19 Pro (3 نانومتر)، وذاكرة عشوائية تصل إلى 12 جيجابايت، مع كاميرات خلفية بدقة 48 ميجابكسل، وبطارية بسعة 4823 مللي أمب",
    "img": "images/products/p221_0_onmdyv.jpg",
    "imgs": [
      "images/products/p221_0_onmdyv.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 220,
    "cat": "new",
    "name": "iphone 17 promax 256 orange",
    "storage": "256GB · orange",
    "color": "orangeذهبي",
    "colorHex": "#ffb514",
    "brand": "apple",
    "price": "96000",
    "originalPrice": "100000",
    "description": "يتميز آيفون 17 برو ماكس (iPhone 17 Pro Max) بشاشة ضخمة 6.9 بوصة من نوع LTPO OLED، ومعالج Apple A19 Pro (3 نانومتر)، وذاكرة عشوائية تصل إلى 12 جيجابايت، مع كاميرات خلفية بدقة 48 ميجابكسل، وبطارية بسعة 4823 مللي أمب",
    "img": "images/products/p220_0_h8m1i0.jpg",
    "imgs": [
      "images/products/p220_0_h8m1i0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  }
];

window.ELKING_BRAND = {
  whatsapp: "201017955559",
  phones: ["01017955559","01017955559","01017955559"],
};
