// El King Store — shared product catalog
// آخر تحديث: ٤‏/١٠‏/٢٠٢٦، ١٢:٠٥:٤١ ص
window.ELKING_PRODUCTS = [
  {
    "id": 587,
    "cat": "used",
    "name": "iphone17promax256 apm 1",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#736626",
    "brand": "Apple",
    "price": "5122",
    "originalPrice": "988492",
    "description": "njnnnm",
    "img": "images/products/p587_0_ke429v.jpg",
    "imgs": [
      "images/products/p587_0_ke429v.jpg"
    ],
    "featured": false,
    "variants": [
      {
        "color": "",
        "colorHex": "#cb3434",
        "price": "",
        "originalPrice": "",
        "imgs": [
          "images/products/p587_v0_0_3coftm.jpg"
        ]
      }
    ],
    "inStock": true,
    "battery": "90",
    "condition": "جيد"
  },
  {
    "id": 586,
    "cat": "used",
    "name": "",
    "storage": "",
    "color": "",
    "colorHex": "",
    "brand": "",
    "price": "",
    "originalPrice": "",
    "description": "",
    "img": "",
    "imgs": [],
    "featured": false,
    "variants": [],
    "inStock": true
  },
  {
    "id": 585,
    "cat": "used",
    "name": "honor magic 5pro s",
    "storage": "16/512",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "HONOR",
    "price": "25500",
    "originalPrice": "27000",
    "description": "",
    "img": "images/products/p585_0_3coftm.jpg",
    "imgs": [
      "images/products/p585_0_3coftm.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 584,
    "cat": "used",
    "name": "samsung a35 s",
    "storage": "8/256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Samsung",
    "price": "15000",
    "originalPrice": "16500",
    "description": "",
    "img": "images/products/p584_0_g7un5v.jpg",
    "imgs": [
      "images/products/p584_0_g7un5v.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 583,
    "cat": "used",
    "name": "oppo a6pro 4g s",
    "storage": "8/256",
    "color": "أحمر",
    "colorHex": "#dc2626",
    "brand": "oppo",
    "price": "15500",
    "originalPrice": "17000",
    "description": "",
    "img": "images/products/p583_0_ke429v.jpg",
    "imgs": [
      "images/products/p583_0_ke429v.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 582,
    "cat": "used",
    "name": "samsung a36 s",
    "storage": "8/256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Samsung",
    "price": "17500",
    "originalPrice": "19000",
    "description": "",
    "img": "images/products/p582_0_7se60p.jpg",
    "imgs": [
      "images/products/p582_0_7se60p.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 581,
    "cat": "used",
    "name": "samsung a56 s",
    "storage": "8/256",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Samsung",
    "price": "22500",
    "originalPrice": "23500",
    "description": "",
    "img": "images/products/p581_0_q2t8q4.jpg",
    "imgs": [
      "images/products/p581_0_q2t8q4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 580,
    "cat": "used",
    "name": "iphone17pro max 256 s",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "80000",
    "originalPrice": "85000",
    "description": "",
    "img": "images/products/p580_0_7sh5uh.jpg",
    "imgs": [
      "images/products/p580_0_7sh5uh.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "99",
    "condition": "ممتاز"
  },
  {
    "id": 579,
    "cat": "used",
    "name": "samsung s25 ultra s",
    "storage": "256",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Samsung",
    "price": "58000",
    "originalPrice": "60000",
    "description": "active",
    "img": "images/products/p579_0_sk4pj3.jpg",
    "imgs": [
      "images/products/p579_0_sk4pj3.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 578,
    "cat": "used",
    "name": "iphone13 128 s",
    "storage": "",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "28000",
    "originalPrice": "29000",
    "description": "",
    "img": "images/products/p578_0_y99sib.jpg",
    "imgs": [
      "images/products/p578_0_y99sib.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "86",
    "condition": "ممتاز"
  },
  {
    "id": 577,
    "cat": "used",
    "name": "iphone13 128  s",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "31000",
    "description": "",
    "img": "images/products/p577_0_y99sib.jpg",
    "imgs": [
      "images/products/p577_0_y99sib.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "88",
    "condition": "جيد"
  },
  {
    "id": 576,
    "cat": "used",
    "name": "iphone13 128 s",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "30000",
    "originalPrice": "32000",
    "description": "",
    "img": "images/products/p576_0_y99sib.jpg",
    "imgs": [
      "images/products/p576_0_y99sib.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "92",
    "condition": "ممتاز"
  },
  {
    "id": 575,
    "cat": "used",
    "name": "iphone13 128 s",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "27000",
    "originalPrice": "28500",
    "description": "",
    "img": "images/products/p575_0_y99sib.jpg",
    "imgs": [
      "images/products/p575_0_y99sib.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 574,
    "cat": "used",
    "name": "iphone14 128 s",
    "storage": "128",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "29000",
    "originalPrice": "31000",
    "description": "",
    "img": "images/products/p574_0_51l2or.jpg",
    "imgs": [
      "images/products/p574_0_51l2or.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "78",
    "condition": "جيد"
  },
  {
    "id": 573,
    "cat": "used",
    "name": "iphone14 128 s",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "30000",
    "originalPrice": "33000",
    "description": "",
    "img": "images/products/p573_0_5ysidh.jpg",
    "imgs": [
      "images/products/p573_0_5ysidh.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "85",
    "condition": "جيد"
  },
  {
    "id": 572,
    "cat": "used",
    "name": "iphone17 256 s",
    "storage": "256",
    "color": "أخضر",
    "colorHex": "#16a34a",
    "brand": "Apple",
    "price": "65000",
    "originalPrice": "67000",
    "description": "عدد الشحنات 60",
    "img": "images/products/p572_0_d5r38h.jpg",
    "imgs": [
      "images/products/p572_0_d5r38h.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 571,
    "cat": "used",
    "name": "iphone 15 128 s",
    "storage": "128",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "34000",
    "originalPrice": "36000",
    "description": "",
    "img": "images/products/p571_0_qb0226.jpg",
    "imgs": [
      "images/products/p571_0_qb0226.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "82",
    "condition": "جيد"
  },
  {
    "id": 570,
    "cat": "used",
    "name": "iphone 16 pro max 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "60000",
    "originalPrice": "63000",
    "description": "عدد الشحنات 574 شحنه",
    "img": "images/products/p570_0_8h1nb5.jpg",
    "imgs": [
      "images/products/p570_0_8h1nb5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91",
    "condition": "جيد"
  },
  {
    "id": 569,
    "cat": "used",
    "name": "iphone 16 pro max 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "64000",
    "originalPrice": "66000",
    "description": "عدد الشحنات 513 شحنه",
    "img": "images/products/p569_0_8h1nb5.jpg",
    "imgs": [
      "images/products/p569_0_8h1nb5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91",
    "condition": "ممتاز"
  },
  {
    "id": 568,
    "cat": "used",
    "name": "iphone 16 pro max 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "63000",
    "originalPrice": "65000",
    "description": "",
    "img": "images/products/p568_0_8h1nb5.jpg",
    "imgs": [
      "images/products/p568_0_8h1nb5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "91",
    "condition": "جيد"
  },
  {
    "id": 567,
    "cat": "used",
    "name": "iphone 16 pro max 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "68000",
    "originalPrice": "70000",
    "description": "عدد الشحنات 184",
    "img": "images/products/p567_0_8h1nb5.jpg",
    "imgs": [
      "images/products/p567_0_8h1nb5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "97",
    "condition": "ممتاز"
  },
  {
    "id": 566,
    "cat": "used",
    "name": "iphone16promax 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "70000",
    "originalPrice": "73000",
    "description": "عدد الشحنات 79",
    "img": "images/products/p566_0_o2f1l7.jpg",
    "imgs": [
      "images/products/p566_0_o2f1l7.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 565,
    "cat": "used",
    "name": "iphone17promax 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "86000",
    "originalPrice": "89000",
    "description": "عدد 22 شحنه",
    "img": "images/products/p565_0_gs57gk.jpg",
    "imgs": [
      "images/products/p565_0_gs57gk.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 564,
    "cat": "used",
    "name": "iphone17promax 256 s",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "86000",
    "originalPrice": "89000",
    "description": "عدد 86 شحنه",
    "img": "images/products/p564_0_c3rg2i.jpg",
    "imgs": [
      "images/products/p564_0_c3rg2i.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 563,
    "cat": "used",
    "name": "iphone17promax 256 s",
    "storage": "98",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "80000",
    "originalPrice": "84000",
    "description": "",
    "img": "images/products/p563_0_kmw557.jpg",
    "imgs": [
      "images/products/p563_0_kmw557.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "98",
    "condition": "ممتاز"
  },
  {
    "id": 562,
    "cat": "used",
    "name": "iphone17promax 512 s",
    "storage": "512",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "95000",
    "originalPrice": "97000",
    "description": "عدد 5 شحنات",
    "img": "images/products/p562_0_flqah5.jpg",
    "imgs": [
      "images/products/p562_0_flqah5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 561,
    "cat": "used",
    "name": "samsung a15 k",
    "storage": "6/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "9000",
    "originalPrice": "10000",
    "description": "",
    "img": "images/products/p561_0_28inu3.jpg",
    "imgs": [
      "images/products/p561_0_28inu3.jpg",
      "images/products/p561_1_ic5noq.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "جيد"
  },
  {
    "id": 560,
    "cat": "used",
    "name": "samsung a35 k",
    "storage": "8/256",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "13000",
    "originalPrice": "14500",
    "description": "",
    "img": "images/products/p560_0_28inu3.jpg",
    "imgs": [
      "images/products/p560_0_28inu3.jpg",
      "images/products/p560_1_ic5noq.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 559,
    "cat": "used",
    "name": "samsung a56 k",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "21500",
    "originalPrice": "23000",
    "description": "",
    "img": "images/products/p559_0_tlv2r6.jpg",
    "imgs": [
      "images/products/p559_0_tlv2r6.jpg",
      "images/products/p559_1_mjpq9z.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 558,
    "cat": "used",
    "name": "samsung a56 k",
    "storage": "12/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "23000",
    "originalPrice": "25000",
    "description": "",
    "img": "images/products/p558_0_j0eg63.jpg",
    "imgs": [
      "images/products/p558_0_j0eg63.jpg",
      "images/products/p558_1_swv7xu.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 557,
    "cat": "used",
    "name": "samsung s25 ultra k",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Samsung",
    "price": "55000",
    "originalPrice": "57000",
    "description": "",
    "img": "images/products/p557_0_m38vru.jpg",
    "imgs": [
      "images/products/p557_0_m38vru.jpg",
      "images/products/p557_1_v5yyp0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": "ممتاز"
  },
  {
    "id": 556,
    "cat": "used",
    "name": "iphone16pro max 256 k",
    "storage": "256",
    "color": "Titanium",
    "colorHex": "#8e8e93",
    "brand": "Apple",
    "price": "65000",
    "originalPrice": "67500",
    "description": "",
    "img": "images/products/p556_0_f9twkk.jpg",
    "imgs": [
      "images/products/p556_0_f9twkk.jpg",
      "images/products/p556_1_cuijpm.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "92",
    "condition": "ممتاز"
  },
  {
    "id": 555,
    "cat": "used",
    "name": "iphone16pro max 256 k",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "59000",
    "originalPrice": "62000",
    "description": "",
    "img": "images/products/p555_0_rnc0zx.jpg",
    "imgs": [
      "images/products/p555_0_rnc0zx.jpg",
      "images/products/p555_1_i0b65s.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "88",
    "condition": "ممتاز"
  },
  {
    "id": 554,
    "cat": "used",
    "name": "iphone16 max 256 k",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "62000",
    "originalPrice": "65000",
    "description": "",
    "img": "images/products/p554_0_8al4r6.jpg",
    "imgs": [
      "images/products/p554_0_8al4r6.jpg",
      "images/products/p554_1_9iqgp8.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "89",
    "condition": "ممتاز"
  },
  {
    "id": 553,
    "cat": "used",
    "name": "iphone16pro max 256 k",
    "storage": "256",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "66500",
    "originalPrice": "67000",
    "description": "",
    "img": "images/products/p553_0_3vmqun.jpg",
    "imgs": [
      "images/products/p553_0_3vmqun.jpg",
      "images/products/p553_1_pzari1.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "94",
    "condition": "ممتاز"
  },
  {
    "id": 552,
    "cat": "used",
    "name": "iphone16pro max 256 k",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "69000",
    "originalPrice": "73000",
    "description": "",
    "img": "images/products/p552_0_8s5q22.jpg",
    "imgs": [
      "images/products/p552_0_8s5q22.jpg",
      "images/products/p552_1_k9jwa9.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "99%",
    "condition": "ممتاز"
  },
  {
    "id": 551,
    "cat": "used",
    "name": "iphone15 128 k",
    "storage": "128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "36500",
    "originalPrice": "39000",
    "description": "",
    "img": "images/products/p551_0_767fd2.jpg",
    "imgs": [
      "images/products/p551_0_767fd2.jpg",
      "images/products/p551_1_u7hnf8.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "85%",
    "condition": "ممتاز"
  },
  {
    "id": 550,
    "cat": "used",
    "name": "iphone14promax 256 k",
    "storage": "256",
    "color": "Deep Purple",
    "colorHex": "#5e548e",
    "brand": "Apple",
    "price": "43000",
    "originalPrice": "45000",
    "description": "",
    "img": "images/products/p550_0_z110rf.jpg",
    "imgs": [
      "images/products/p550_0_z110rf.jpg",
      "images/products/p550_1_io7eue.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "81%",
    "condition": "جيد"
  },
  {
    "id": 549,
    "cat": "used",
    "name": "iphone 12 promax 256 k",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "27000",
    "originalPrice": "30000",
    "description": "battry 75%\nfull box",
    "img": "images/products/p549_0_wr64p1.jpg",
    "imgs": [
      "images/products/p549_0_wr64p1.jpg",
      "images/products/p549_1_2pa4nc.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "75%",
    "condition": "جيد"
  },
  {
    "id": 548,
    "cat": "used",
    "name": "iphone 17 promax 256 k",
    "storage": "256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "8100",
    "originalPrice": "85000",
    "description": "94% battry\nfull box\norange",
    "img": "images/products/p548_0_pl9dml.jpg",
    "imgs": [
      "images/products/p548_0_pl9dml.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "94",
    "condition": "ممتاز"
  },
  {
    "id": 547,
    "cat": "used",
    "name": "iphone15plus 128 k",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "35000",
    "originalPrice": "37000",
    "description": "بحالة الزيرو \nعدد شحنات 59 شحنه",
    "img": "images/products/p547_0_vmxwsq.jpg",
    "imgs": [
      "images/products/p547_0_vmxwsq.jpg",
      "images/products/p547_1_e0m2vw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "100",
    "condition": "ممتاز"
  },
  {
    "id": 546,
    "cat": "used",
    "name": "iphone15 128 k",
    "storage": "128",
    "color": "Iceblue",
    "colorHex": "#a0cfec",
    "brand": "Apple",
    "price": "39000",
    "originalPrice": "42000",
    "description": "حاله ممتازه لا يوجد اى خدوش كرتونه كامله",
    "img": "images/products/p546_0_m2zjpe.jpg",
    "imgs": [
      "images/products/p546_0_m2zjpe.jpg",
      "images/products/p546_1_3a3urq.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "93",
    "condition": "ممتاز"
  },
  {
    "id": 545,
    "cat": "used",
    "name": "iphone 17 promax 512 k",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "93000",
    "originalPrice": "95000",
    "description": "battry 99%  \n512g\nfull box",
    "img": "images/products/p545_0_8o2dp4.jpg",
    "imgs": [
      "images/products/p545_0_8o2dp4.jpg",
      "images/products/p545_1_spj6th.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "99",
    "condition": "ممتاز"
  },
  {
    "id": 544,
    "cat": "new",
    "name": "",
    "storage": "",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "",
    "price": "",
    "originalPrice": "",
    "description": "",
    "img": "",
    "imgs": [],
    "featured": false,
    "variants": [
      {
        "color": "",
        "colorHex": "#c46464",
        "price": "",
        "originalPrice": "",
        "imgs": []
      }
    ],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 543,
    "cat": "new",
    "name": "HONOR X9d",
    "storage": "12/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "HONOR",
    "price": "22700",
    "originalPrice": "23500",
    "description": "أعلنت شركة هونر عن هاتفها الجديد الـ HONOR X9d لينافس بقوة في الفئة المتوسطة بأكبر بطارية 8300 مللي أمبير تدعم شحن سريع 66 واط بالأضافة لمعالج جيد من كوالكم Snapdragon 6 Gen 4 مع كاميرا خلفية 108 ميجا بكسل وسيلفي 16 ميجا بكسل وبالطبع أعلى حماية ممكنة من الماء والأتربة والصدمات",
    "img": "images/products/p543_0_vnnhc4.jpg",
    "imgs": [
      "images/products/p543_0_vnnhc4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 542,
    "cat": "new",
    "name": "HONOR X6c",
    "storage": "6/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "HONOR",
    "price": "11900",
    "originalPrice": "12500",
    "description": "أعلنت شركة هونر عن هاتفها الجديد الـ HONOR X6c لينافس في الفئة الاقتصادية بخامات عالية مقاومة للصدمات وبطارية 5300 مللي أمبير وشحن سريع بقوة 35 واط بالأضافة لكاميرا خلفية 50 ميجا بيكسل ومعالج Mediatek Helio G81 Ultra .",
    "img": "images/products/p542_0_km68lk.jpg",
    "imgs": [
      "images/products/p542_0_km68lk.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 541,
    "cat": "new",
    "name": "HONOR X6c",
    "storage": "6/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "HONOR",
    "price": "12950",
    "originalPrice": "13500",
    "description": "أعلنت شركة هونر عن هاتفها الجديد الـ HONOR X6c لينافس في الفئة الاقتصادية بخامات عالية مقاومة للصدمات وبطارية 5300 مللي أمبير وشحن سريع بقوة 35 واط بالأضافة لكاميرا خلفية 50 ميجا بيكسل ومعالج Mediatek Helio G81 Ultra .",
    "img": "images/products/p541_0_km68lk.jpg",
    "imgs": [
      "images/products/p541_0_km68lk.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 540,
    "cat": "new",
    "name": "HONOR 600",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "HONOR",
    "price": "28000",
    "originalPrice": "30000",
    "description": "أعلنت شركة هونر عن هاتفها الجديد الـ HONOR 600 لينافس بقوة في الفئة المتوسطة مع تطويرات واضحة مثل التصميم الجديد بفريم معدني فخم واستخدام معالج قوي من كوالكم Snapdragon 7 Gen 4 بالأضاضة لشاشة أموليد مسطحة بدقة 1.5K وسطوع خارق تحت الشمس مع كاميرا خلفية 200 ميجا بيكسل وبطارية عملاقة 7000 مللي أمبير تدعم شحن سريع بقوة 80 واط",
    "img": "images/products/p540_0_tadssd.jpg",
    "imgs": [
      "images/products/p540_0_tadssd.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 539,
    "cat": "new",
    "name": "HONOR 600",
    "storage": "12/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "HONOR",
    "price": "12950",
    "originalPrice": "14000",
    "description": "أعلنت شركة هونر عن هاتفها الجديد الـ HONOR 600 لينافس بقوة في الفئة المتوسطة مع تطويرات واضحة مثل التصميم الجديد بفريم معدني فخم واستخدام معالج قوي من كوالكم Snapdragon 7 Gen 4 بالأضاضة لشاشة أموليد مسطحة بدقة 1.5K وسطوع خارق تحت الشمس مع كاميرا خلفية 200 ميجا بيكسل وبطارية عملاقة 7000 مللي أمبير تدعم شحن سريع بقوة 80 واط",
    "img": "images/products/p539_0_tadssd.jpg",
    "imgs": [
      "images/products/p539_0_tadssd.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 538,
    "cat": "new",
    "name": "HONOR Magic 7 Pro",
    "storage": "12/512",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "HONOR",
    "price": "57000",
    "originalPrice": "60000",
    "description": "أعلنت شركة هونر عن هاتفها الرائد الجديد الـ HONOR Magic 7 Pro لينافس بشراسة حيث يأتي بمعالج رائد من شركة كوالكم Snapdragon 8 Elite لتحصل على أقوى أداء متوفر في الوقت الحالي مع كاميرات خلفية مميزة تعطيك تجربة مثالية أثناء الاستخدام مع زوم قوي حتى 100X مع شاشة كبيرة منحنية بشكل الثقب المزدوج في منتصف الشاشة مع بطارية كبيرة السعة 5850 مللي أمبير تدعم الشحن السريع بقوة 100 واط بخلاف دعم الشحن الوايرلس",
    "img": "images/products/p538_0_bfcdvs.jpg",
    "imgs": [
      "images/products/p538_0_bfcdvs.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 537,
    "cat": "new",
    "name": "Infinix smart 20",
    "storage": "4/128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Infinix",
    "price": "8300",
    "originalPrice": "8500",
    "description": "أعلنت شركة انفنكس عن هاتفها الاقتصادي الـ Infinix Smart 20 واستخدمت انفنكس معالج من ميدياتيك G81 لتحصل على أداء مقبول مع شاشة بشكل الثقب بمعدل تحديث 120Hz بالأضافة لتصميم شيك ولكن مع بطارية 5200 مللي أمبير",
    "img": "images/products/p537_0_ptphw.jpg",
    "imgs": [
      "images/products/p537_0_ptphw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 536,
    "cat": "new",
    "name": "Infinix smart 20",
    "storage": "4/64",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Infinix",
    "price": "7000",
    "originalPrice": "7300",
    "description": "أعلنت شركة انفنكس عن هاتفها الاقتصادي الـ Infinix Smart 20 واستخدمت انفنكس معالج من ميدياتيك G81 لتحصل على أداء مقبول مع شاشة بشكل الثقب بمعدل تحديث 120Hz بالأضافة لتصميم شيك ولكن مع بطارية 5200 مللي أمبير",
    "img": "images/products/p536_0_ptphw.jpg",
    "imgs": [
      "images/products/p536_0_ptphw.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 535,
    "cat": "new",
    "name": "Poco C85",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Xiaomi",
    "price": "10850",
    "originalPrice": "19500",
    "description": "أعلنت شركة شاومي عن هاتفها الجديد الـ Xiaomi Poco C85 4G الذي يعتبر نسخة من Redmi 15C حيث يأتي بشاشة كبيرة بشكل النوتش بمساحة 6.9 إنش بدقة HD+ وتردد 120 هيرتز مع معالج من ميدياتيك Helio G81 Ultra يقدم اداء اقتصادي مع كاميرا سيلفي 8 ميجا بكسل وكاميرا خلفية 50 ميجا بكسل مع الاهتمام بالبطارية فتأتي بسعة 6000 مللي أمبير لتضمن لك العمل لفترة طويلة خلال اليوم مع دعم الشحن السريع بقوة 33 واط",
    "img": "images/products/p535_0_rtt5pd.jpg",
    "imgs": [
      "images/products/p535_0_rtt5pd.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 534,
    "cat": "new",
    "name": "Redmi 15C",
    "storage": "6/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Xiaomi",
    "price": "10950",
    "originalPrice": "11500",
    "description": "أعلنت شركة شاومي عن هاتفها الاقتصادي الجديد الـ Xiaomi Redmi 15C 4G الذي يأتي بتصميم جديد بخامات راقية مع بطارية عملاقة 6000 مللي أمبير وشحن أسرع 33 واط مع نفس المعالج الاقتصادي G81 Ultra وكاميرا خلفية 50 ميجا بيكسل وشاشة كبيرة IPS بتردد 120 هيرتز .. فدعونا نتعرف على المواصفات الكاملة لهاتف Xiaomi Redmi 15C 4G",
    "img": "images/products/p534_0_acu8qf.jpg",
    "imgs": [
      "images/products/p534_0_acu8qf.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 533,
    "cat": "new",
    "name": "Redmi 15C",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Xiaomi",
    "price": "11500",
    "originalPrice": "12000",
    "description": "أعلنت شركة شاومي عن هاتفها الاقتصادي الجديد الـ Xiaomi Redmi 15C 4G الذي يأتي بتصميم جديد بخامات راقية مع بطارية عملاقة 6000 مللي أمبير وشحن أسرع 33 واط مع نفس المعالج الاقتصادي G81 Ultra وكاميرا خلفية 50 ميجا بيكسل وشاشة كبيرة IPS بتردد 120 هيرتز .. فدعونا نتعرف على المواصفات الكاملة لهاتف Xiaomi Redmi 15C 4G",
    "img": "images/products/p533_0_acu8qf.jpg",
    "imgs": [
      "images/products/p533_0_acu8qf.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 532,
    "cat": "new",
    "name": "Redmi 15 4G",
    "storage": "6/128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Xiaomi",
    "price": "11100",
    "originalPrice": "12000",
    "description": "أعلنت شركة شاومي عن هاتفها الجديد الـ Xiaomi Redmi 15 4G في الفئة الاقتصادية والهاتف يركز على البطارية بشكل كبير حيث يأتي بأضخم بطارية في فئته 7000 مللي أمبير مع شحن سريع 33 واط وشحن سريع عكسي 18 واط بالأضافة لشاشة كبيرة 6.9 بوصة بتردد 144Hz ومعالج من نوع Snapdragon 685 .",
    "img": "images/products/p532_0_sx6vv.jpg",
    "imgs": [
      "images/products/p532_0_sx6vv.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 531,
    "cat": "new",
    "name": "Redmi 15 4G",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Xiaomi",
    "price": "13100",
    "originalPrice": "14500",
    "description": "أعلنت شركة شاومي عن هاتفها الجديد الـ Xiaomi Redmi 15 4G في الفئة الاقتصادية والهاتف يركز على البطارية بشكل كبير حيث يأتي بأضخم بطارية في فئته 7000 مللي أمبير مع شحن سريع 33 واط وشحن سريع عكسي 18 واط بالأضافة لشاشة كبيرة 6.9 بوصة بتردد 144Hz ومعالج من نوع Snapdragon 685",
    "img": "images/products/p531_0_sx6vv.jpg",
    "imgs": [
      "images/products/p531_0_sx6vv.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 530,
    "cat": "new",
    "name": "Redmi 17 4G",
    "storage": "6/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Xiaomi",
    "price": "12000",
    "originalPrice": "13500",
    "description": "أعلنت شركة شاومي عن هاتفها الاقتصادي الجديد الـ Xiaomi Redmi 17 4G الذي يأتي ببطارية كبيرة 7500 مللي أمبير مع شحن سريع 45 واط بالأضافة لتصميم شيك مع شاشة كبيرة 6.9 بوصة من نوع IPS تدعم معدل التحديث الـ 120Hz بالأضافة لمعالج ميدياتيك الاقتصادي Helio G91 Ultra مع كاميرا خلفية 50 ميجا بيكسل وسيلفي 8 ميجا بيكسل",
    "img": "images/products/p530_0_j77bd2.jpg",
    "imgs": [
      "images/products/p530_0_j77bd2.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 529,
    "cat": "new",
    "name": "Redmi Note 15 4g",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Xiaomi",
    "price": "16400",
    "originalPrice": "15500",
    "description": "أعلنت شركة شاومي عن هاتفها الجديد الـ Xiaomi Redmi Note 15 4G وهو أقل فرد في السلسلة ولكن يأتي بشاشة أموليد منحنية ممتازة بمساحة 6.77 بوصة بدقة FHD+ تدعم الـ 120 هرتز مع معالج ميدياتيك Helio G100 Ultra وكاميرا خلفية بدقة 108 ميجا بكسل مع كاميرا سيلفي 20 ميجا بكسل وصوت ستريو بالأضافة لبطارية كبيرة بسعة 6000 مللي أمبير تدعم الشحن السريع 33 واط",
    "img": "images/products/p529_0_2h8cl7.jpg",
    "imgs": [
      "images/products/p529_0_2h8cl7.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 528,
    "cat": "new",
    "name": "Redmi Note 15 5G",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Xiaomi",
    "price": "17800",
    "originalPrice": "18500",
    "description": "أعلنت شاومي عن هاتفها الجديد الـ Xiaomi Redmi Note 15 5G لينافس في بداية الفئة المتوسطة بمعالج من كوالكم SD 6 Gen 3 داعم لشبكات الجيل الخامس ويقدم اداء جيد بالأضافة لشاشة منحنية بتردد 120 هيرتز مع كاميرا خلفية 108 ميجا بيكسل بمثبت بصري بالأضافة لصوت ستريو وبطارية 5520 مللي أمبير تدعم شحن سريع 45 واط",
    "img": "images/products/p528_0_5d1kad.jpg",
    "imgs": [
      "images/products/p528_0_5d1kad.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 527,
    "cat": "new",
    "name": "oppo a6x",
    "storage": "4/64",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "8950",
    "originalPrice": "9500",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6x 4G والذي يأتي لينافس في الفئة الاقتصادية بمعالج من نوع Snapdragon 685 ليقدم تجربة تصفح جيدة مع شاشة كبيرة بمساحة 6.75 بوصة مع دعم معدل التحديث الـ 120 هرتز بالأضافة لبطارية كبيرة السعة 6500 مللي أمبير",
    "img": "images/products/p527_0_i4ivxv.jpg",
    "imgs": [
      "images/products/p527_0_i4ivxv.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 526,
    "cat": "new",
    "name": "oppo a6x",
    "storage": "4/128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "10600",
    "originalPrice": "11500",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6x 4G والذي يأتي لينافس في الفئة الاقتصادية بمعالج من نوع Snapdragon 685 ليقدم تجربة تصفح جيدة مع شاشة كبيرة بمساحة 6.75 بوصة مع دعم معدل التحديث الـ 120 هرتز بالأضافة لبطارية كبيرة السعة 6500 مللي أمبير",
    "img": "images/products/p526_0_i4ivxv.jpg",
    "imgs": [
      "images/products/p526_0_i4ivxv.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 525,
    "cat": "new",
    "name": "oppo a6",
    "storage": "4/128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "11800",
    "originalPrice": "19500",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6  لينضم بشكل رسمي إلى سلسلة الـ A وأهم ما يميز الهاتف البطارية الكبيرة 7000 مللي أمبير وشحن 45 واط بالأضافة لمقاومة عالية ضيةد الماء بمعيار IP68/IP69 مع معالج Dimensity 6300 داعم لشبكات الجيل الخامس وصوت ستريو ولكن مع شاشة وكاميرا من الفئة الاقتصاد",
    "img": "images/products/p525_0_ij3fth.jpg",
    "imgs": [
      "images/products/p525_0_ij3fth.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 524,
    "cat": "new",
    "name": "oppo a6",
    "storage": "6/128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "15900",
    "originalPrice": "17000",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد Oppo A6 لينضم بشكل رسمي إلى سلسلة الـ A وأهم ما يميز الهاتف البطارية الكبيرة 7000 مللي أمبير وشحن 45 واط بالأضافة لمقاومة عالية ضد الماء بمعيار IP68/IP69 مع معالج Dimensity 6300 داعم لشبكات الجيل الخامس وصوت ستريو ولكن مع شاشة وكاميرا من الفئة الاقتصادية",
    "img": "images/products/p524_0_ij3fth.jpg",
    "imgs": [
      "images/products/p524_0_ij3fth.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 523,
    "cat": "new",
    "name": "oppo a6 pro 5g",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "20500",
    "originalPrice": "22000",
    "description": "أعلنت شركة Oppo عن هاتفها الجديد في الفئة المتوسطة الـ Oppo A6 Pro 4G داعم لشبكات الجيل الخامس بمعالج من ميدياتيك من نوع Dimensity 6300 مع شاشة أموليد FHD+ بتردد 120 هيرتز وسطوع عالي مع كاميرا سيلفي 16 ميجا بكسل وكاميرا خلفية 50 ميجا بكسل مع بطارية ضخمة 7000 مللي أمبير تدعم شحن سريع بقوة 80 واط .",
    "img": "images/products/p523_0_tg4d8w.jpg",
    "imgs": [
      "images/products/p523_0_tg4d8w.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 522,
    "cat": "new",
    "name": "oppo reno16f",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "26700",
    "originalPrice": "30000",
    "description": "أعلنت شركة اوبو عن هاتفها المتوسط الجديد الـ Oppo Reno 16 F الذي يأتي بمعالج أفضل من الجيل السابق Dimensity 7300 Energy مع كاميرات جيدة واضافة عدسة مخصصة للزوم لأول مرة في فئة F من الرينو مع بطارية عملاقة 7000 مللي أمبير تدعم شحن سريع بقدرة 80 واط بالأضافة لشاشة أموليد مسطحة 120 هيرتز",
    "img": "images/products/p522_0_o79j1s.jpg",
    "imgs": [
      "images/products/p522_0_o79j1s.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 521,
    "cat": "new",
    "name": "oppo reno16f 5g",
    "storage": "12/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "30700",
    "originalPrice": "32000",
    "description": "أعلنت شركة اوبو عن هاتفها المتوسط الجديد الـ Oppo Reno 16 F الذي يأتي بمعالج أفضل من الجيل السابق Dimensity 7300 Energy مع كاميرات جيدة واضافة عدسة مخصصة للزوم لأول مرة في فئة F من الرينو مع بطارية عملاقة 7000 مللي أمبير تدعم شحن سريع بقدرة 80 واط بالأضافة لشاشة أموليد مسطحة 120 هيرتز",
    "img": "images/products/p521_0_o79j1s.jpg",
    "imgs": [
      "images/products/p521_0_o79j1s.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 520,
    "cat": "new",
    "name": "oppo reno16 5g",
    "storage": "12/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "oppo",
    "price": "36400",
    "originalPrice": "37500",
    "description": "أعلنت شركة أوبو عن هاتفها الجديد الـ Oppo Reno 16 لينافس كالعادة في الفئة المتوسطة العليا بتصميم فخم زجاج مع المونيوم بالأضافة لشاشة أصغر في الحجم ولكنها بجودة ممتازة مع معالج كالعادة من كوالكم SD 7 Gen 4 مع نظام كاميرا قوي 50 ميجا بيكسل في كل العدسات اساسية وزوم والترا وايد وسيلفي مع دعم تصوير فيديو 4K بكل العدسات بالأضافة لبطارية كبيرة 6700 مللي",
    "img": "images/products/p520_0_88813b.jpg",
    "imgs": [
      "images/products/p520_0_88813b.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 519,
    "cat": "new",
    "name": "samsung a07",
    "storage": "4/64",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "8650",
    "originalPrice": "9500",
    "description": "أعلنت شركة سامسونج عن هاتفها الاقتصادي الجديد الـ Samsung Galaxy A07 ليقدم أفضل اداء في الفئة الاقتصادية بمعالج من ميدياتيك Helio G99 وتحديثات لمدة 6 سنين مع تصميم بسيط وشاشة كبيرة 6.7 بوصة بتردد 90 هيرتز بالأضافة لكاميرا خلفية 50 ميجا بيكسل وسيلفي 8 ميجا بيكسل",
    "img": "images/products/p519_0_djmvy4.jpg",
    "imgs": [
      "images/products/p519_0_djmvy4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 517,
    "cat": "new",
    "name": "samsung a07",
    "storage": "4/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "8650",
    "originalPrice": "9000",
    "description": "أعلنت شركة سامسونج عن هاتفها الاقتصادي الجديد الـ Samsung Galaxy A07 ليقدم أفضل اداء في الفئة الاقتصادية بمعالج من ميدياتيك Helio G99 وتحديثات لمدة 6 سنين مع تصميم بسيط وشاشة كبيرة 6.7 بوصة بتردد 90 هيرتز بالأضافة لكاميرا خلفية 50 ميجا بيكسل وسيلفي 8 ميجا بيكسل",
    "img": "images/products/p517_0_djmvy4.jpg",
    "imgs": [
      "images/products/p517_0_djmvy4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 516,
    "cat": "new",
    "name": "samsung a07",
    "storage": "6/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "10850",
    "originalPrice": "13000",
    "description": "أعلنت شركة سامسونج عن هاتفها الاقتصادي الجديد الـ Samsung Galaxy A07 ليقدم أفضل اداء في الفئة الاقتصادية بمعالج من ميدياتيك Helio G99 وتحديثات لمدة 6 سنين مع تصميم بسيط وشاشة كبيرة 6.7 بوصة بتردد 90 هيرتز بالأضافة لكاميرا خلفية 50 ميجا بيكسل وسيلفي 8 ميجا بيكسل",
    "img": "images/products/p516_0_djmvy4.jpg",
    "imgs": [
      "images/products/p516_0_djmvy4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 515,
    "cat": "new",
    "name": "samsung a07",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "12900",
    "originalPrice": "13500",
    "description": "أعلنت شركة سامسونج عن هاتفها الاقتصادي الجديد الـ Samsung Galaxy A07 ليقدم أفضل اداء في الفئة الاقتصادية بمعالج من ميدياتيك Helio G99 وتحديثات لمدة 6 سنين مع تصميم بسيط وشاشة كبيرة 6.7 بوصة بتردد 90 هيرتز بالأضافة لكاميرا خلفية 50 ميجا بيكسل وسيلفي 8 ميجا بيكسل",
    "img": "images/products/p515_0_djmvy4.jpg",
    "imgs": [
      "images/products/p515_0_djmvy4.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 514,
    "cat": "new",
    "name": "samsung a26",
    "storage": "8/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "16500",
    "originalPrice": "17500",
    "description": "أعلنت شركة سامسونج عن هاتفها الـ Samsung Galaxy A26 لينافس في بداية الفئة المتوسطة حيث يأتي بمعالج قوي من نوع Exynos 1380 مع كاميرا خلفية 50 ميجا بكسل بمثبت بصري وكاميرا أمامية بدقة 13 ميجا بكسل بخلاف التصميم الزجاجي ومقاومة الماء IP67 مع بطارية بقوة 5000 مللي أمبير",
    "img": "images/products/p514_0_9z82q0.jpg",
    "imgs": [
      "images/products/p514_0_9z82q0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 513,
    "cat": "new",
    "name": "samsung a27",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "18200",
    "originalPrice": "19000",
    "description": "أعلنت شركة سامسونج عن هاتفها الـ Samsung Galaxy A26 لينافس في بداية الفئة المتوسطة حيث يأتي بمعالج قوي من نوع Exynos 1380 مع كاميرا خلفية 50 ميجا بكسل بمثبت بصري وكاميرا أمامية بدقة 13 ميجا بكسل بخلاف التصميم الزجاجي ومقاومة الماء IP67 مع بطارية بقوة 5000 مللي أمبير",
    "img": "images/products/p513_0_9z82q0.jpg",
    "imgs": [
      "images/products/p513_0_9z82q0.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 512,
    "cat": "new",
    "name": "samsung a17",
    "storage": "6/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "12950",
    "originalPrice": "13500",
    "description": "علنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A17  الذي يأتي لينافس في بداية الفئة المتوسطة بمعالج Exynos 1330 داعم لشبكات الجيل الخامس مع شاشة من نوع Super AMOLED تدعم معدل التحديث الـ 90Hz مع كاميرا أمامية 13 ميجا بكسل وكاميرا خلفية رئيسية 50 ميجا بكسل بمثبت بصري مع بطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 25 واط",
    "img": "images/products/p512_0_bu6uvl.jpg",
    "imgs": [
      "images/products/p512_0_bu6uvl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 511,
    "cat": "new",
    "name": "samsung a17",
    "storage": "4/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "11250",
    "originalPrice": "12500",
    "description": "علنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A17  الذي يأتي لينافس في بداية الفئة المتوسطة بمعالج Exynos 1330 داعم لشبكات الجيل الخامس مع شاشة من نوع Super AMOLED تدعم معدل التحديث الـ 90Hz مع كاميرا أمامية 13 ميجا بكسل وكاميرا خلفية رئيسية 50 ميجا بكسل بمثبت بصري مع بطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 25 واط",
    "img": "images/products/p511_0_bu6uvl.jpg",
    "imgs": [
      "images/products/p511_0_bu6uvl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 510,
    "cat": "new",
    "name": "samsung a17",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "15900",
    "originalPrice": "16500",
    "description": "علنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A17  الذي يأتي لينافس في بداية الفئة المتوسطة بمعالج Exynos 1330 داعم لشبكات الجيل الخامس مع شاشة من نوع Super AMOLED تدعم معدل التحديث الـ 90Hz مع كاميرا أمامية 13 ميجا بكسل وكاميرا خلفية رئيسية 50 ميجا بكسل بمثبت بصري مع بطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 25 واط",
    "img": "images/products/p510_0_bu6uvl.jpg",
    "imgs": [
      "images/products/p510_0_bu6uvl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 509,
    "cat": "new",
    "name": "samsung a17 5g",
    "storage": "6/128",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "13250",
    "originalPrice": "14500",
    "description": "علنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A17 5G الذي يأتي لينافس في بداية الفئة المتوسطة بمعالج Exynos 1330 داعم لشبكات الجيل الخامس مع شاشة من نوع Super AMOLED تدعم معدل التحديث الـ 90Hz مع كاميرا أمامية 13 ميجا بكسل وكاميرا خلفية رئيسية 50 ميجا بكسل بمثبت بصري مع بطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 25 واط",
    "img": "images/products/p509_0_bu6uvl.jpg",
    "imgs": [
      "images/products/p509_0_bu6uvl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 508,
    "cat": "new",
    "name": "samsung a17 5g",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "18200",
    "originalPrice": "19500",
    "description": "علنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A17 5g  الذي يأتي لينافس في بداية الفئة المتوسطة بمعالج Exynos 1330 داعم لشبكات الجيل الخامس مع شاشة من نوع Super AMOLED تدعم معدل التحديث الـ 90Hz مع كاميرا أمامية 13 ميجا بكسل وكاميرا خلفية رئيسية 50 ميجا بكسل بمثبت بصري مع بطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 25 واط",
    "img": "images/products/p508_0_bu6uvl.jpg",
    "imgs": [
      "images/products/p508_0_bu6uvl.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 507,
    "cat": "new",
    "name": "samsung a37",
    "storage": "8/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "22000",
    "originalPrice": "23000",
    "description": "أعلنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A37 لينافس في الفئة المتوسطة بشاشة أموليد 6.7 بوصة بدقة FHD+ تدعم 120Hz مع معالج من سامسونج وهو الـ Exynos 1480 يقدم اداء جيد في الاستخدامات اليومية وفي تجربة الكاميرات حيث يأتي الهاتف بكاميرا خلفية رئيسية 50 ميجا بيكسل وسيلفي 12 ميجا بكسل مع دعم صوت ستريو وبطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 45 واط",
    "img": "images/products/p507_0_v4eo1k.jpg",
    "imgs": [
      "images/products/p507_0_v4eo1k.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 506,
    "cat": "new",
    "name": "samsung a37",
    "storage": "12/256",
    "color": "",
    "colorHex": "#0a0a0a",
    "brand": "Samsung",
    "price": "24400",
    "originalPrice": "25000",
    "description": "أعلنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A37 لينافس في الفئة المتوسطة بشاشة أموليد 6.7 بوصة بدقة FHD+ تدعم 120Hz مع معالج من سامسونج وهو الـ Exynos 1480 يقدم اداء جيد في الاستخدامات اليومية وفي تجربة الكاميرات حيث يأتي الهاتف بكاميرا خلفية رئيسية 50 ميجا بيكسل وسيلفي 12 ميجا بكسل مع دعم صوت ستريو وبطارية 5000 مللي أمبير تدعم الشحن السريع بقوة 45 واط",
    "img": "images/products/p506_0_v4eo1k.jpg",
    "imgs": [
      "images/products/p506_0_v4eo1k.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 505,
    "cat": "new",
    "name": "samsung a57",
    "storage": "8/256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "26500",
    "originalPrice": "30500",
    "description": "أعلنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A57 الذي ينافس في الفئة المتوسطة العليا بأرقى خامات فريم معدن وظهر زجاج بحماية عالية ومقاومة ماء IP68 بالأضافة لمعالج جديد من سامسونج Exynos 1680 يقدم تجربة جيدة مع كاميرات مميزة ولكن بدون عدسة زوم وشاشة مميزة من نوع Super AMOLED Plus بدقة FHD+ تدعم 120Hz بحواف أقل عن الأجيال السابقة مع دعم سماعات ستيريو وبطارية 5000 مللي أمبير تدعم شحن سريع بقوة 45 واط",
    "img": "images/products/p505_0_9ylr6z.jpg",
    "imgs": [
      "images/products/p505_0_9ylr6z.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 504,
    "cat": "new",
    "name": "samsung a57",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "28900",
    "originalPrice": "32000",
    "description": "أعلنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A57 الذي ينافس في الفئة المتوسطة العليا بأرقى خامات فريم معدن وظهر زجاج بحماية عالية ومقاومة ماء IP68 بالأضافة لمعالج جديد من سامسونج Exynos 1680 يقدم تجربة جيدة مع كاميرات مميزة ولكن بدون عدسة زوم وشاشة مميزة من نوع Super AMOLED Plus بدقة FHD+ تدعم 120Hz بحواف أقل عن الأجيال السابقة مع دعم سماعات ستيريو وبطارية 5000 مللي أمبير تدعم شحن سريع بقوة 45 واط",
    "img": "images/products/p504_0_9ylr6z.jpg",
    "imgs": [
      "images/products/p504_0_9ylr6z.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 503,
    "cat": "new",
    "name": "samsung a57",
    "storage": "512",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "33000",
    "originalPrice": "35000",
    "description": "أعلنت شركة سامسونج عن هاتفها الجديد الـ Samsung Galaxy A57 الذي ينافس في الفئة المتوسطة العليا بأرقى خامات فريم معدن وظهر زجاج بحماية عالية ومقاومة ماء IP68 بالأضافة لمعالج جديد من سامسونج Exynos 1680 يقدم تجربة جيدة مع كاميرات مميزة ولكن بدون عدسة زوم وشاشة مميزة من نوع Super AMOLED Plus بدقة FHD+ تدعم 120Hz بحواف أقل عن الأجيال السابقة مع دعم سماعات ستيريو وبطارية 5000 مللي أمبير تدعم شحن سريع بقوة 45 واط",
    "img": "images/products/p503_0_9ylr6z.jpg",
    "imgs": [
      "images/products/p503_0_9ylr6z.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 502,
    "cat": "new",
    "name": "samsung s25 ultra",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "60000",
    "originalPrice": "63000",
    "description": "أهلا بكم في عصر تطور الذكاء الأصطناعي مع أحدث وأقوى هواتف سامسونج الرائدة الـ Samsung Galaxy S25 Ultra حيث قامت سامسونج بتغيير لغة التصميم فأصبحت حواف الهاتف دائرية وليست حادة مع فريم مسطح تماما مع الحفاظ على الشاشة المسطحة الممتازة ولكن بحجم أكبر 6.9 بوصة بحواف أقل مع استخدام معالج كوالكم الرائد الجديد SD 8 Elite الذي يقدم اداء قوي جدا مع تغيير عدسة التصوير الالترا وايد لتكون 50 ميجا بيكسل والحفاظ على بقية مواصفات الهاتف ولكن مع استخدام واجهة سامسونج الجديدة ومميزات ذكاء اصطناعي تفاعليه جديدة",
    "img": "images/products/p502_0_7dtcdq.jpg",
    "imgs": [
      "images/products/p502_0_7dtcdq.jpg"
    ],
    "featured": true,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 501,
    "cat": "new",
    "name": "samsung s26 ultra",
    "storage": "1t",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "90000",
    "originalPrice": "95000",
    "description": "أقوى موبايل رائد من سامسونج وبالتأكيد ملك الذكاء الأصطناعي الـ Samsung Galaxy S26 Ultra الذي يأتي بشاشة لأول مرة في العالم Privacy Display والتي ستحافظ على خصوصيتك من المتطفلين مع الاهتمام بالأداء حيث يأتي بمعالج Snapdragon 8 Elite Gen 5 بالأضافة لبطارية 5000 مللي أمبير تدعم شحن أسرع بقوة 60 واط وشحن لاسلكي بقوة 25 واط مع نظام كاميرات مُحسن من ناحية التصوير الليلي ..",
    "img": "images/products/p501_0_jyf24a.jpg",
    "imgs": [
      "images/products/p501_0_jyf24a.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 500,
    "cat": "new",
    "name": "samsung s26 ultra 512",
    "storage": "512",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "75000",
    "originalPrice": "82000",
    "description": "أقوى موبايل رائد من سامسونج وبالتأكيد ملك الذكاء الأصطناعي الـ Samsung Galaxy S26 Ultra الذي يأتي بشاشة لأول مرة في العالم Privacy Display والتي ستحافظ على خصوصيتك من المتطفلين مع الاهتمام بالأداء حيث يأتي بمعالج Snapdragon 8 Elite Gen 5 بالأضافة لبطارية 5000 مللي أمبير تدعم شحن أسرع بقوة 60 واط وشحن لاسلكي بقوة 25 واط مع نظام كاميرات مُحسن من ناحية التصوير الليلي ..",
    "img": "images/products/p500_0_jyf24a.jpg",
    "imgs": [
      "images/products/p500_0_jyf24a.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 499,
    "cat": "new",
    "name": "samsung s26 ultra",
    "storage": "256",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Samsung",
    "price": "67000",
    "originalPrice": "69000",
    "description": "أقوى موبايل رائد من سامسونج وبالتأكيد ملك الذكاء الأصطناعي الـ Samsung Galaxy S26 Ultra الذي يأتي بشاشة لأول مرة في العالم Privacy Display والتي ستحافظ على خصوصيتك من المتطفلين مع الاهتمام بالأداء حيث يأتي بمعالج Snapdragon 8 Elite Gen 5 بالأضافة لبطارية 5000 مللي أمبير تدعم شحن أسرع بقوة 60 واط وشحن لاسلكي بقوة 25 واط مع نظام كاميرات مُحسن من ناحية التصوير الليلي ..",
    "img": "images/products/p499_0_jyf24a.jpg",
    "imgs": [
      "images/products/p499_0_jyf24a.jpg"
    ],
    "featured": false,
    "variants": [
      {
        "color": "",
        "colorHex": "#0A0A0A",
        "price": "",
        "originalPrice": "",
        "imgs": []
      }
    ],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 498,
    "cat": "new",
    "name": "iphone15 128",
    "storage": "128",
    "color": "أبيض",
    "colorHex": "#f5f5f5",
    "brand": "Apple",
    "price": "46500",
    "originalPrice": "47500",
    "description": "هاتف iPhone 15 هو أصغر هاتف في سلسلة أبل الجديد ويتميز بحجم صغير ومواصفات قوية حيث يأتي بمعالج A16 Bionic القوي وكاميرا خلفية أفضل 48 ميجا بيكسل مع بطارية أقوى من الجيل السابق بالاضافة لشاشة بشكل Dynamic Island .. فدعونا نتعرف على المواصفات الكاملة لهاتف",
    "img": "images/products/p498_0_lmi44n.jpg",
    "imgs": [
      "images/products/p498_0_lmi44n.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 497,
    "cat": "new",
    "name": "iphone17promax256",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "65000",
    "originalPrice": "67000",
    "description": "ابل عن هاتفها الأقوى الـ iPhone 17 Pro Max لينافس الهواتف الرائدة بقوة مع تصميم جديد كليا للموبايل مع شكل جديد للكاميرا الخلفية وتطوير كبير في الهاتف من ناحية المعالج الأحدث الـ A19 Pro مع غرفة تبريد للحفاظ على الهاتف من الحرارة مع عدسة سيلفي جديدة 18 ميجا بيكسل وعدسة زوم مُحدثة 48 ميجا بيكسل مع بطارية أكبر بالأضافة لشاشة كبيرة 6.9 بوصة بسطوع أعلى وصوت ستريو ممتاز كالعادة",
    "img": "images/products/p497_0_pxryv3.jpg",
    "imgs": [
      "images/products/p497_0_pxryv3.jpg"
    ],
    "featured": true,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 496,
    "cat": "new",
    "name": "iphone17",
    "storage": "256",
    "color": "أسود",
    "colorHex": "#0a0a0a",
    "brand": "Apple",
    "price": "51000",
    "originalPrice": "54000",
    "description": "أعلنت شركة ابل عن هاتفها الجديد الـ iPhone 17 الذي يُمثل نقلة نوعية بالنسبة لهواتف أبل السابقة حيث تم تغيير الشاشة لتدعم التردد المتغير من 1 لـ 120 هيرتز مع سطوع أعلى وحماية أقوى بالأضافة لمعالج جديد من أبل A19 يقدم أداء أقوى مع سيلفي جديد كليا 18 ميجا بيكسل وعدسة الترا وايد 48 ميجا بيكسل بالأضافة لبطارية أكبر",
    "img": "images/products/p496_0_39g5es.jpg",
    "imgs": [
      "images/products/p496_0_39g5es.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 495,
    "cat": "new",
    "name": "iphone17 active",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "49000",
    "originalPrice": "52000",
    "description": "أعلنت شركة ابل عن هاتفها الجديد الـ iPhone 17 الذي يُمثل نقلة نوعية بالنسبة لهواتف أبل السابقة حيث تم تغيير الشاشة لتدعم التردد المتغير من 1 لـ 120 هيرتز مع سطوع أعلى وحماية أقوى بالأضافة لمعالج جديد من أبل A19 يقدم أداء أقوى مع سيلفي جديد كليا 18 ميجا بيكسل وعدسة الترا وايد 48 ميجا بيكسل بالأضافة لبطارية أكبر",
    "img": "images/products/p495_0_39g5es.jpg",
    "imgs": [
      "images/products/p495_0_39g5es.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 494,
    "cat": "new",
    "name": "iphone air apm",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "65000",
    "originalPrice": "70000",
    "description": "أعلنت شركة أبل عن هاتفها الجديد الـ iPhone Air الذي يأتي بتصميم ثوري ليكون أنحف وأخف هاتف من ابل مقارنة بالإصدارات السابقة حيث يأتي بسمك 5.6 ملم فقط مع وزن خفيف 165 جرام مع فريم من التيتانيوم وشاشة كبيرة 6.5 بوصة بتردد سريع متغير 120 هيرتز وسطوع عالي بالأضافة لمعالج أبل الأقوى A19 Pro بتقنية 3 نانومتر والسيلفي الجديد الـ 18 ميجا بيكسل بمستشعر مربع",
    "img": "images/products/p494_0_8vert.jpg",
    "imgs": [
      "images/products/p494_0_8vert.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 493,
    "cat": "new",
    "name": "iphone17promax512 apm",
    "storage": "512",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "75000",
    "originalPrice": "82000",
    "description": "ابل عن هاتفها الأقوى الـ iPhone 17 Pro Max لينافس الهواتف الرائدة بقوة مع تصميم جديد كليا للموبايل مع شكل جديد للكاميرا الخلفية وتطوير كبير في الهاتف من ناحية المعالج الأحدث الـ A19 Pro مع غرفة تبريد للحفاظ على الهاتف من الحرارة مع عدسة سيلفي جديدة 18 ميجا بيكسل وعدسة زوم مُحدثة 48 ميجا بيكسل مع بطارية أكبر بالأضافة لشاشة كبيرة 6.9 بوصة بسطوع أعلى وصوت ستريو ممتاز كالعادة",
    "img": "images/products/p493_0_pxryv3.jpg",
    "imgs": [
      "images/products/p493_0_pxryv3.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 492,
    "cat": "new",
    "name": "iphone17promax256 apm",
    "storage": "256",
    "color": "أزرق",
    "colorHex": "#1e40af",
    "brand": "Apple",
    "price": "89500",
    "originalPrice": "92000",
    "description": "ابل عن هاتفها الأقوى الـ iPhone 17 Pro Max لينافس الهواتف الرائدة بقوة مع تصميم جديد كليا للموبايل مع شكل جديد للكاميرا الخلفية وتطوير كبير في الهاتف من ناحية المعالج الأحدث الـ A19 Pro مع غرفة تبريد للحفاظ على الهاتف من الحرارة مع عدسة سيلفي جديدة 18 ميجا بيكسل وعدسة زوم مُحدثة 48 ميجا بيكسل مع بطارية أكبر بالأضافة لشاشة كبيرة 6.9 بوصة بسطوع أعلى وصوت ستريو ممتاز كالعادة",
    "img": "images/products/p492_0_4zv2g5.jpg",
    "imgs": [
      "images/products/p492_0_4zv2g5.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 491,
    "cat": "new",
    "name": "iphone17promax256 apm",
    "storage": "256",
    "color": "ذهبي",
    "colorHex": "#d4af37",
    "brand": "Apple",
    "price": "89500",
    "originalPrice": "92000",
    "description": "ابل عن هاتفها الأقوى الـ iPhone 17 Pro Max لينافس الهواتف الرائدة بقوة مع تصميم جديد كليا للموبايل مع شكل جديد للكاميرا الخلفية وتطوير كبير في الهاتف من ناحية المعالج الأحدث الـ A19 Pro مع غرفة تبريد للحفاظ على الهاتف من الحرارة مع عدسة سيلفي جديدة 18 ميجا بيكسل وعدسة زوم مُحدثة 48 ميجا بيكسل مع بطارية أكبر بالأضافة لشاشة كبيرة 6.9 بوصة بسطوع أعلى وصوت ستريو ممتاز كالعادة",
    "img": "images/products/p491_0_sbct5c.jpg",
    "imgs": [
      "images/products/p491_0_sbct5c.jpg"
    ],
    "featured": true,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  },
  {
    "id": 490,
    "cat": "new",
    "name": "iphone17promax256 apm",
    "storage": "256",
    "color": "فضي",
    "colorHex": "#c0c0c0",
    "brand": "Apple",
    "price": "89500",
    "originalPrice": "92000",
    "description": "ابل عن هاتفها الأقوى الـ iPhone 17 Pro Max لينافس الهواتف الرائدة بقوة مع تصميم جديد كليا للموبايل مع شكل جديد للكاميرا الخلفية وتطوير كبير في الهاتف من ناحية المعالج الأحدث الـ A19 Pro مع غرفة تبريد للحفاظ على الهاتف من الحرارة مع عدسة سيلفي جديدة 18 ميجا بيكسل وعدسة زوم مُحدثة 48 ميجا بيكسل مع بطارية أكبر بالأضافة لشاشة كبيرة 6.9 بوصة بسطوع أعلى وصوت ستريو ممتاز كالعادة",
    "img": "images/products/p490_0_pxryv3.jpg",
    "imgs": [
      "images/products/p490_0_pxryv3.jpg"
    ],
    "featured": false,
    "variants": [],
    "inStock": true,
    "battery": "",
    "condition": ""
  }
];

window.ELKING_BRAND = {
  whatsapp: "201017955559",
  phones: ["01017955559","01017955559","01017955559"],
};
